import type { AutomationRow, AutomationRunRow, Json } from '../types/database'
import { requireSupabase, throwServiceError } from './api'

export async function listAutomations(organizationId:string):Promise<AutomationRow[]>{const {data,error}=await requireSupabase().from('automations').select('*').eq('organization_id',organizationId).order('created_at',{ascending:false});if(error)throwServiceError(error,'Unable to load automations.');return data??[]}
export async function listAutomationRuns(organizationId:string):Promise<AutomationRunRow[]>{const {data,error}=await requireSupabase().from('automation_runs').select('*').eq('organization_id',organizationId).order('started_at',{ascending:false}).limit(20);if(error)throwServiceError(error,'Unable to load automation runs.');return data??[]}
export async function createAutomation(organizationId:string,name:string,condition:Json,action:Json){const client=requireSupabase();const {data:{user}}=await client.auth.getUser();const {data,error}=await client.from('automations').insert({organization_id:organizationId,name,trigger_type:'LEAD_CREATED',created_by:user?.id??null,status:'ACTIVE'}).select().single();if(error)throwServiceError(error,'Unable to create automation.');const steps=[{automation_id:data.id,organization_id:organizationId,step_type:'CONDITION' as const,position:0,config:condition},{automation_id:data.id,organization_id:organizationId,step_type:'ACTION' as const,position:1,config:action}];const {error:stepError}=await client.from('automation_steps').insert(steps);if(stepError)throwServiceError(stepError,'Unable to save automation steps.');return data}
export async function setAutomationStatus(id:string,organizationId:string,status:AutomationRow['status']){const {error}=await requireSupabase().from('automations').update({status,updated_at:new Date().toISOString()}).eq('id',id).eq('organization_id',organizationId);if(error)throwServiceError(error,'Unable to update automation.')}
export async function runAutomation(automationId:string,leadId:string,triggerEvent='MANUAL_TEST'){const {data,error}=await requireSupabase().functions.invoke('automation-run',{body:{automationId,leadId,triggerEvent}});if(error)throwServiceError(error,'Unable to run automation.');return data as {status:string}}
export async function runTriggeredAutomations(organizationId:string,leadId:string,triggerType:string){const items=await listAutomations(organizationId);return Promise.allSettled(items.filter(item=>item.status==='ACTIVE'&&item.trigger_type===triggerType).map(item=>runAutomation(item.id,leadId,triggerType)))}
