import type { AutomationRow, AutomationRunRow, Json } from '../types/database'
import { requireSupabase, throwServiceError } from './api'

export async function listAutomations(organizationId:string):Promise<AutomationRow[]>{const {data,error}=await requireSupabase().from('automations').select('*').eq('organization_id',organizationId).order('created_at',{ascending:false});if(error)throwServiceError(error,'Unable to load automations.');return data??[]}
export async function listAutomationRuns(organizationId:string):Promise<AutomationRunRow[]>{const {data,error}=await requireSupabase().from('automation_runs').select('*').eq('organization_id',organizationId).order('started_at',{ascending:false}).limit(20);if(error)throwServiceError(error,'Unable to load automation runs.');return data??[]}
export async function createAutomation(organizationId:string,name:string,condition:Json,action:Json){const score=typeof condition==='object'&&condition&&!Array.isArray(condition)?Number(condition.value):NaN;const actionType=typeof action==='object'&&action&&!Array.isArray(action)?String(action.type):'';const delay=typeof action==='object'&&action&&!Array.isArray(action)?Number(action.delayHours??24):24;const {data,error}=await requireSupabase().rpc('create_automation_workflow',{target_org:organizationId,workflow_name:name,minimum_score:score,action_type:actionType,delay_hours:delay});if(error)throwServiceError(error,'Unable to save automation.');return data}
export async function setAutomationStatus(id:string,organizationId:string,status:AutomationRow['status']){const {error}=await requireSupabase().from('automations').update({status,updated_at:new Date().toISOString()}).eq('id',id).eq('organization_id',organizationId);if(error)throwServiceError(error,'Unable to update automation.')}
export async function runAutomation(automationId:string,leadId:string,triggerEvent='MANUAL_TEST',dryRun=triggerEvent==='MANUAL_TEST'){const {data,error}=await requireSupabase().functions.invoke('automation-run',{body:{automationId,leadId,triggerEvent,dryRun}});if(error)throwServiceError(error,'Unable to run automation.');return data as {status:string;actions?:string[];dryRun?:boolean}}
export async function runTriggeredAutomations(organizationId:string,leadId:string,triggerType:string){const items=await listAutomations(organizationId);return Promise.allSettled(items.filter(item=>item.status==='ACTIVE'&&item.trigger_type===triggerType).map(item=>runAutomation(item.id,leadId,triggerType)))}
