import type {ConversationReadRow,ConversationRow,MessageRow} from '../types/database'
import {requireSupabase,throwServiceError} from './api'
export async function listConversations(organizationId:string):Promise<ConversationRow[]>{const {data,error}=await requireSupabase().from('conversations').select('*').eq('organization_id',organizationId).order('last_message_at',{ascending:false,nullsFirst:false}).limit(100);if(error)throwServiceError(error,'Unable to load conversations.');return data??[]}
export async function listConversationMessages(organizationId:string,conversationId:string):Promise<MessageRow[]>{const {data,error}=await requireSupabase().from('messages').select('*').eq('organization_id',organizationId).eq('conversation_id',conversationId).order('created_at').limit(250);if(error)throwServiceError(error,'Unable to load messages.');return data??[]}
export async function listConversationReads(organizationId:string):Promise<ConversationReadRow[]>{const {data,error}=await requireSupabase().from('conversation_reads').select('*').eq('organization_id',organizationId);if(error)throwServiceError(error,'Unable to load inbox state.');return data??[]}
export async function createConversation(organizationId:string,contactId:string|null,channel:ConversationRow['channel']){const {data,error}=await requireSupabase().rpc('create_conversation',{target_org:organizationId,target_contact:contactId,conversation_channel:channel});if(error)throwServiceError(error,'Unable to create conversation.');return data}
export async function sendConversationMessage(organizationId:string,conversationId:string,body:string){const {data,error}=await requireSupabase().rpc('send_conversation_message',{target_org:organizationId,target_conversation:conversationId,message_body:body});if(error)throwServiceError(error,'Unable to send message.');return data}
export async function markConversationRead(organizationId:string,conversationId:string){const {data,error}=await requireSupabase().rpc('mark_conversation_read',{target_org:organizationId,target_conversation:conversationId});if(error)throwServiceError(error,'Unable to mark conversation read.');return data}
export async function setConversationStatus(organizationId:string,conversationId:string,status:ConversationRow['status']){const {data,error}=await requireSupabase().from('conversations').update({status,updated_at:new Date().toISOString()}).eq('organization_id',organizationId).eq('id',conversationId).select().single();if(error)throwServiceError(error,'Unable to update conversation.');return data}
