import {requireSupabase,throwServiceError} from './api'
import type {NotificationPreferenceRow,WidgetConfigRow} from '../types/database'

export async function getWidgetConfig(organizationId:string){const {data,error}=await requireSupabase().from('widget_configs').select('*').eq('organization_id',organizationId).maybeSingle();if(error)throwServiceError(error,'Unable to load widget settings.');return data}
export async function saveWidgetConfig(input:WidgetConfigRow){const {data,error}=await requireSupabase().from('widget_configs').upsert(input).select().single();if(error)throwServiceError(error,'Unable to save widget settings.');return data}
export async function getNotificationPreferences(organizationId:string,userId:string){const {data,error}=await requireSupabase().from('notification_preferences').select('*').eq('organization_id',organizationId).eq('user_id',userId).maybeSingle();if(error)throwServiceError(error,'Unable to load notification preferences.');return data}
export async function saveNotificationPreferences(input:NotificationPreferenceRow){const {data,error}=await requireSupabase().from('notification_preferences').upsert({...input,updated_at:new Date().toISOString()}).select().single();if(error)throwServiceError(error,'Unable to save notification preferences.');return data}
export async function exportWorkspace(organizationId:string){const client=requireSupabase();const tables=['contacts','leads','lead_activities','tasks','conversations','messages','knowledge_items','automations','automation_runs'] as const;const entries=await Promise.all(tables.map(async table=>{const {data,error}=await client.from(table).select('*').eq('organization_id',organizationId);if(error)throw error;return [table,data] as const}));return Object.fromEntries(entries)}
export async function deleteWorkspace(organizationId:string,name:string){const {error}=await requireSupabase().rpc('delete_organization',{target_org:organizationId,confirmation:name});if(error)throwServiceError(error,'Unable to delete workspace.')}
