import {expect,test} from '@playwright/test'

test.beforeEach(async({page})=>{
  await page.goto('/#app')
  await page.evaluate(()=>{sessionStorage.setItem('nexara-demo-mode','true');localStorage.removeItem('nexara-demo-modules-v1');localStorage.removeItem('nexara-demo-workspace-v2')})
  await page.reload()
})

test('new conversations open a form, save messages, and retain them after reload',async({page})=>{
  await page.locator('.sidebar nav').getByRole('button',{name:'Inbox'}).click()
  await page.getByRole('button',{name:'New conversation'}).click()
  const dialog=page.getByRole('dialog',{name:'New conversation'})
  await expect(dialog).toBeVisible()
  await dialog.getByLabel('Contact').selectOption('contact-lead-aisha')
  await dialog.getByRole('button',{name:'Create conversation'}).click()
  await page.getByPlaceholder('Write a reply…').fill('I can arrange a viewing tomorrow.')
  await page.getByRole('button',{name:'Send ↗'}).click()
  await expect(page.locator('.message-history')).toContainText('I can arrange a viewing tomorrow.')
  await page.reload()
  await page.locator('.sidebar nav').getByRole('button',{name:'Inbox'}).click()
  await page.locator('.conversation-list').getByRole('button',{name:/Aisha Njeri.*I can arrange/}).click()
  await expect(page.locator('.message-history')).toContainText('I can arrange a viewing tomorrow.')
})

test('knowledge items can be created and edited',async({page})=>{
  await page.locator('.sidebar nav').getByRole('button',{name:'Knowledge'}).click()
  await page.getByRole('button',{name:'Add knowledge'}).click()
  const dialog=page.getByRole('dialog',{name:'Add knowledge'})
  await dialog.getByLabel('Title').fill('Office hours')
  await dialog.getByLabel('Content').fill('Open Monday through Friday.')
  await dialog.getByRole('button',{name:'Save knowledge'}).click()
  await expect(page.locator('.knowledge-grid')).toContainText('Office hours')
  await page.getByRole('button',{name:'Edit item'}).first().click()
  await page.getByRole('dialog',{name:'Edit knowledge'}).getByLabel('Content').fill('Open weekdays 9 to 5.')
  await page.getByRole('dialog',{name:'Edit knowledge'}).getByRole('button',{name:'Save knowledge'}).click()
  await expect(page.locator('.knowledge-grid')).toContainText('Open weekdays 9 to 5.')
})

test('automation configurations save and preview without changing lead stage',async({page})=>{
  await page.locator('.sidebar nav').getByRole('button',{name:'Automations'}).click()
  await page.getByLabel('Minimum lead score').fill('80')
  await page.getByLabel('Workflow action').selectOption('set_stage')
  await page.getByRole('button',{name:'Save and activate'}).click()
  await expect(page.locator('.automation-catalog')).toContainText('score ≥ 80')
  await page.getByLabel('Test lead').selectOption('lead-james')
  await page.getByRole('button',{name:'Run test'}).click()
  await expect(page.locator('.automation-side')).toContainText('James Mwangi matches')
  await page.locator('.sidebar nav').getByRole('button',{name:'Leads'}).click()
  await expect(page.getByLabel('Stage for James Mwangi')).toHaveValue('Qualified')
  await page.reload()
  await page.locator('.sidebar nav').getByRole('button',{name:'Automations'}).click()
  await expect(page.locator('.automation-catalog')).toContainText('score ≥ 80')
})

test('overview links navigate and settings save the demo organization',async({page})=>{
  await page.getByRole('button',{name:'View all'}).click()
  await expect(page.getByRole('heading',{name:'Leads'})).toBeVisible()
  await page.locator('.sidebar-bottom').getByRole('button',{name:'Settings'}).click()
  await page.getByLabel('Business name').fill('Demo Agency')
  await page.getByRole('button',{name:'Save changes'}).click()
  await page.reload()
  await page.locator('.sidebar-bottom').getByRole('button',{name:'Settings'}).click()
  await expect(page.getByLabel('Business name')).toHaveValue('Demo Agency')
})

test('scheduled follow-ups appear in Tasks and survive reload',async({page})=>{
  await page.locator('.sidebar nav').getByRole('button',{name:'Leads'}).click()
  await page.getByRole('button',{name:/James Mwangi/}).first().click()
  await page.getByLabel('Follow-up date').fill('2026-10-02T10:00')
  await page.getByRole('button',{name:'Schedule',exact:true}).click()
  await page.getByRole('button',{name:'Close profile'}).click()
  await page.locator('.sidebar nav').getByRole('button',{name:'Tasks'}).click()
  await expect(page.getByText('Lead follow-up')).toBeVisible()
  await page.reload()
  await page.locator('.sidebar nav').getByRole('button',{name:'Tasks'}).click()
  await expect(page.getByText('Lead follow-up')).toBeVisible()
})

test('billing preview selects a plan and shows its price',async({page})=>{
  await page.locator('.sidebar nav').getByRole('button',{name:'Billing'}).click()
  await page.getByRole('button',{name:'Preview plan'}).nth(1).click()
  await expect(page.getByRole('status')).toContainText('Growth')
  await expect(page.getByRole('status')).toContainText('KSh 7,500')
})
