import { expect, test } from '@playwright/test'

test.beforeEach(async ({ page }) => {
  await page.goto('/#app')
  await page.evaluate(() => { localStorage.removeItem('nexara-demo-workspace-v2'); sessionStorage.setItem('nexara-demo-mode','true') })
  await page.reload()
})

test('configured production routes require a session while demo access remains explicit',async({page})=>{
  await page.evaluate(()=>sessionStorage.removeItem('nexara-demo-mode'))
  await page.reload()
  await expect(page.getByRole('heading',{name:'Good to see you again.'})).toBeVisible()
  await page.getByRole('button',{name:'Explore the demo instead'}).click()
  await expect(page.getByRole('heading',{name:/Good morning/})).toBeVisible()
})

test('creates a complete lead, opens its profile and persists it after reload', async ({ page }) => {
  await page.locator('.sidebar nav').getByRole('button', { name: 'Leads' }).click()
  await page.getByRole('button', { name: 'Add lead' }).click()
  const dialog = page.getByRole('dialog', { name: 'Add a lead' })
  await dialog.getByLabel('Full name').fill('Grace Wambui')
  await dialog.getByLabel('Interest').fill('Commercial office · Upper Hill')
  await dialog.getByLabel('Email', { exact: true }).fill('grace@example.com')
  await dialog.getByLabel('Phone').fill('+254 700 111 222')
  await dialog.getByLabel('Company').fill('Wambui Studio')
  await dialog.getByLabel('Budget / value').fill('KSh 35M')
  await dialog.getByLabel('Source').selectOption('Referral')
  await dialog.getByLabel('Owner').selectOption('Sarah')
  await dialog.getByLabel('Stage').selectOption('Qualified')
  await dialog.getByLabel('Lead score').fill('91')
  await dialog.getByLabel('Next action').fill('Arrange site visit')
  await dialog.getByLabel(/Tags/).fill('High intent, Office')
  await dialog.getByLabel(/Custom fields/).fill('Preferred floor: 8th\nParking bays: 2')
  await dialog.getByRole('button', { name: 'Create lead' }).click()
  const profile = page.getByRole('dialog').filter({ hasText: 'Grace Wambui' })
  await expect(profile).toContainText('Commercial office · Upper Hill')
  await expect(profile).toContainText('91/100')
  await expect(profile).toContainText('Preferred floor')
  await expect(profile).toContainText('8th')
  await profile.getByRole('button', { name: 'Close profile' }).click()
  await page.reload()
  await page.locator('.sidebar nav').getByRole('button', { name: 'Leads' }).click()
  await page.getByLabel('Search leads').fill('Grace')
  await expect(page.locator('.crm-leads-table tbody')).toContainText('Grace Wambui')
  await expect(page.locator('.crm-leads-table tbody')).toContainText('KSh 35M')
  await page.getByRole('button',{name:'Grace Wambui'}).click()
  await expect(page.getByRole('dialog')).toContainText('Parking bays')
})

test('lead profile records notes, follow-ups, assignment and stage changes', async ({ page }) => {
  await page.locator('.sidebar nav').getByRole('button', { name: 'Leads' }).click()
  await page.getByRole('button', { name: 'James Mwangi' }).click()
  const profile = page.getByRole('dialog').filter({ hasText: 'James Mwangi' })
  await profile.getByLabel('Add note').fill('Customer requested a Saturday morning viewing.')
  await profile.getByRole('button', { name: 'Add note' }).click()
  await expect(profile).toContainText('Customer requested a Saturday morning viewing.')
  await profile.getByLabel('Follow-up date').fill('2026-10-01T09:30')
  await profile.getByRole('button', { name: 'Schedule', exact: true }).click()
  await expect(profile).toContainText('Follow-up scheduled for')
  await profile.locator('.profile-summary').getByRole('combobox').first().selectOption('Meeting')
  await profile.locator('.profile-summary').getByRole('combobox').nth(1).selectOption('Sarah')
  await expect(profile).toContainText('Stage changed to Meeting')
  await expect(profile).toContainText('Assigned to Sarah')
})

test('lead filters, bulk actions and recoverable archive work', async ({ page }) => {
  await page.locator('.sidebar nav').getByRole('button', { name: 'Leads' }).click()
  await page.getByLabel('Filter by stage').selectOption('New')
  await expect(page.locator('.crm-leads-table tbody tr')).toHaveCount(1)
  await page.getByLabel('Select Brian Otieno').check()
  await page.getByRole('button', { name: 'Mark qualified' }).click()
  await expect(page.locator('.crm-empty')).toContainText('No matching leads')
  await page.getByLabel('Filter by stage').selectOption('Qualified')
  await page.getByLabel('Select Brian Otieno').check()
  await page.getByRole('button', { name: 'Archive' }).click()
  await expect(page.locator('.crm-leads-table tbody')).not.toContainText('Brian Otieno')
  const saved = await page.evaluate(() => JSON.parse(localStorage.getItem('nexara-demo-workspace-v2')!))
  expect(saved.leads.find((lead: { id: string }) => lead.id === 'lead-brian').archived).toBe(true)
})

test('pipeline movement persists and opens the same lead record', async ({ page }) => {
  await page.locator('.sidebar nav').getByRole('button', { name: 'Pipeline' }).click()
  await page.getByLabel('Move James Mwangi').selectOption('Meeting')
  await expect(page.getByRole('region', { name: 'Meeting stage' })).toContainText('James Mwangi')
  await page.getByRole('button', { name: /James Mwangi/ }).click()
  await expect(page.getByRole('dialog')).toContainText('Meeting')
  await page.getByRole('button', { name: 'Close profile' }).click()
  await page.reload()
  await page.locator('.sidebar nav').getByRole('button', { name: 'Pipeline' }).click()
  await expect(page.getByLabel('Move James Mwangi')).toHaveValue('Meeting')
})

test('contact creation, editing and relationship history work', async ({ page }) => {
  await page.locator('.sidebar nav').getByRole('button', { name: 'Contacts' }).click()
  await page.getByRole('button', { name: 'Add contact' }).click()
  const dialog = page.getByRole('dialog', { name: 'Add contact' })
  await dialog.getByLabel('Full name').fill('Nia Akinyi')
  await dialog.getByLabel('Company').fill('Nia Design')
  await dialog.getByLabel('Email', { exact: true }).fill('nia@example.com')
  await dialog.getByLabel('Phone').fill('+254 711 222 333')
  await dialog.getByLabel('Type').selectOption('Prospect')
  await dialog.getByLabel('Tags').fill('Designer, Nairobi')
  await dialog.getByRole('button', { name: 'Save contact' }).click()
  await page.getByLabel('Search contacts').fill('Nia')
  await expect(page.locator('.contacts-table tbody')).toContainText('Nia Akinyi')
  await page.locator('.contacts-table tbody tr').click()
  const edit = page.getByRole('dialog', { name: 'Edit contact' })
  await edit.getByLabel('Type').selectOption('Customer')
  await edit.getByRole('button', { name: 'Save contact' }).click()
  await expect(page.locator('.contacts-table tbody')).toContainText('Customer')
  await page.getByLabel('Search contacts').fill('James')
  await expect(page.locator('.contacts-table tbody tr')).toContainText('1')
})

test('contact identity deduplicates matching email and normalized phone',async({page})=>{
  await page.locator('.sidebar nav').getByRole('button',{name:'Contacts'}).click()
  for(const [name,email,phone] of [['First Record','same@example.com','+254 700 123 456'],['Duplicate Email','SAME@example.com',''],['Duplicate Phone','','254700123456']]){
    await page.getByRole('button',{name:'Add contact'}).click();const dialog=page.getByRole('dialog',{name:'Add contact'});await dialog.getByLabel('Full name').fill(name);if(email)await dialog.getByLabel('Email',{exact:true}).fill(email);if(phone)await dialog.getByLabel('Phone').fill(phone);await dialog.getByRole('button',{name:'Save contact'}).click()
  }
  const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('nexara-demo-workspace-v2')!))
  expect(saved.contacts.filter((contact:{email:string;phone:string})=>contact.email.toLowerCase()==='same@example.com'||contact.phone.replace(/\D/g,'')==='254700123456')).toHaveLength(1)
})

test('follow-up tasks can be reviewed, opened and completed',async({page})=>{
  await page.locator('.sidebar nav').getByRole('button',{name:'Tasks'}).click()
  await expect(page.getByRole('heading',{name:'Tasks'})).toBeVisible()
  await expect(page.locator('.task-list')).toContainText('Confirm Saturday viewing')
  await page.getByRole('button',{name:/Open Aisha Njeri/}).click()
  await expect(page.getByRole('dialog')).toContainText('Aisha Njeri')
  await page.getByRole('button',{name:'Close profile'}).click()
  await page.locator('.sidebar nav').getByRole('button',{name:'Tasks'}).click()
  await page.getByRole('button',{name:'Complete Confirm Saturday viewing'}).click()
  await expect(page.locator('.task-list')).toContainText('You’re all caught up')
  await page.getByRole('button',{name:'Completed'}).click()
  await expect(page.locator('.task-list')).toContainText('Confirm Saturday viewing')
})

test('global search, notifications, help and theme are operational', async ({ page }) => {
  await page.keyboard.press('Control+k')
  const search = page.getByRole('dialog', { name: 'Search workspace' })
  await search.getByLabel('Search workspace').fill('James')
  await search.getByRole('button', { name: /James Mwangi/ }).click()
  await expect(page.getByRole('dialog')).toContainText('James Mwangi')
  await page.getByRole('button', { name: 'Close profile' }).click()
  await page.getByRole('button', { name: 'Notifications' }).click()
  await expect(page.locator('.notification-popover')).toBeVisible()
  await page.getByRole('button', { name: 'Mark all read' }).click()
  await expect(page.getByRole('button', { name: 'Notifications' }).locator('i')).toHaveCount(0)
  await page.locator('.sidebar-bottom').getByRole('button', { name: 'Help' }).click()
  await expect(page.getByRole('heading', { name: 'Help centre' })).toBeVisible()
  await page.getByRole('button', { name: 'Open Leads' }).click()
  await expect(page.getByRole('heading', { name: 'Leads' })).toBeVisible()
  await page.getByRole('button', { name: 'Toggle theme' }).click()
  await expect(page.locator('.app')).toHaveClass(/dark/)
  await page.reload()
  await expect(page.locator('.app')).toHaveClass(/dark/)
})

for (const width of [1024, 768, 430, 390]) {
  test(`CRM pages avoid document overflow at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 900 })
    for (const name of ['Leads', 'Pipeline', 'Tasks', 'Contacts']) {
      const mobileToggle = page.getByRole('button', { name: 'Open navigation' })
      if (await mobileToggle.isVisible()) await mobileToggle.click()
      await page.locator('.sidebar nav').getByRole('button', { name }).click()
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
    }
  })
}
