import { useMemo, useState } from 'react'
import type { OwnerOption, TaskDraft, TaskPriority, WorkspaceLead, WorkspaceTask } from '../crm/types'
import './tasks.css'
import './tasks-professional.css'

type Props={tasks:WorkspaceTask[];leads:WorkspaceLead[];owners:OwnerOption[];onComplete:(id:string)=>void|Promise<unknown>;onCreate:(draft:TaskDraft)=>void|Promise<unknown>;onUpdate:(id:string,draft:TaskDraft)=>void|Promise<unknown>;onCancel:(id:string)=>void|Promise<unknown>;onOpenLead:(id:string)=>void;notify:(message:string)=>void}
type View='My queue'|'Today'|'Upcoming'|'Overdue'|'Completed'|'All'
const priorities:TaskPriority[]=['Low','Normal','High','Urgent']
const emptyDraft:TaskDraft={title:'',description:'',dueAt:null,leadId:null,assigneeId:null,priority:'Normal'}
const localInput=(value:string|null)=>value?new Date(new Date(value).getTime()-new Date(value).getTimezoneOffset()*60000).toISOString().slice(0,16):''
const dayStart=()=>{const date=new Date();date.setHours(0,0,0,0);return date}

export function TasksPage({tasks,leads,owners,onComplete,onCreate,onUpdate,onCancel,onOpenLead,notify}:Props){
  const [view,setView]=useState<View>('My queue'),[query,setQuery]=useState(''),[owner,setOwner]=useState('All'),[editing,setEditing]=useState<WorkspaceTask|null>(null),[creating,setCreating]=useState(false),[busy,setBusy]=useState(false)
  const today=dayStart(),tomorrow=new Date(today.getTime()+86400000),week=new Date(today.getTime()+7*86400000)
  const visible=useMemo(()=>tasks.filter(task=>{
    const due=task.dueAt?new Date(task.dueAt):null,search=`${task.title} ${task.description} ${task.leadName}`.toLowerCase()
    if(query&&!search.includes(query.toLowerCase())||owner!=='All'&&task.assigneeId!==owner)return false
    if(view==='Completed')return task.status==='Completed'
    if(view==='All')return true
    if(task.status!=='Open')return false
    if(view==='Overdue')return Boolean(due&&due<today)
    if(view==='Today')return Boolean(due&&due>=today&&due<tomorrow)
    if(view==='Upcoming')return Boolean(due&&due>=tomorrow&&due<week)
    return true
  }).sort((a,b)=>{const rank={Urgent:0,High:1,Normal:2,Low:3};return rank[a.priority]-rank[b.priority]||(a.dueAt??'9999').localeCompare(b.dueAt??'9999')}),[tasks,query,owner,view,today,tomorrow,week])
  const open=tasks.filter(task=>task.status==='Open'),overdue=open.filter(task=>task.dueAt&&new Date(task.dueAt)<today),dueToday=open.filter(task=>task.dueAt&&new Date(task.dueAt)>=today&&new Date(task.dueAt)<tomorrow)
  const complete=async(task:WorkspaceTask)=>{await onComplete(task.id);notify(`${task.title} completed`)}
  return <><div className="page-heading"><div><p className="eyebrow">Agency operations</p><h1>Tasks</h1><p className="subheading">Plan client work, assign ownership and keep every deadline accountable.</p></div><button className="btn primary" onClick={()=>setCreating(true)}>＋ New task</button></div>
    <div className="task-metrics"><button className="card" onClick={()=>setView('My queue')}><strong>{open.length}</strong><span>Open work</span></button><button className="card" onClick={()=>setView('Today')}><strong>{dueToday.length}</strong><span>Due today</span></button><button className="card overdue" onClick={()=>setView('Overdue')}><strong>{overdue.length}</strong><span>Overdue</span></button><div className="card"><strong>{Math.round(tasks.filter(task=>task.status==='Completed').length/Math.max(tasks.length,1)*100)}%</strong><span>Completion rate</span></div></div>
    <div className="task-command card"><div className="task-tabs">{(['My queue','Today','Upcoming','Overdue','Completed','All'] as View[]).map(value=><button className={view===value?'active':''} key={value} onClick={()=>setView(value)}>{value}</button>)}</div><div className="task-filters"><input aria-label="Search tasks" placeholder="Search tasks or clients" value={query} onChange={event=>setQuery(event.target.value)}/><select aria-label="Filter task owner" value={owner} onChange={event=>setOwner(event.target.value)}><option value="All">All assignees</option>{owners.map(item=><option value={item.id} key={item.id}>{item.label}</option>)}</select></div></div>
    <div className="card task-list"><div className="task-list-head"><strong>{view}</strong><span>{visible.length} task{visible.length===1?'':'s'} · sorted by urgency</span></div>{visible.map(task=>{const isOverdue=task.status==='Open'&&Boolean(task.dueAt)&&new Date(task.dueAt!)<today;return <article className={`task-row ${task.status==='Completed'?'complete':''}`} key={task.id}><button className="task-check" disabled={task.status!=='Open'} onClick={()=>void complete(task)} aria-label={`Complete ${task.title}`}>{task.status==='Completed'?'✓':''}</button><span className={`task-priority ${task.priority.toLowerCase()}`}>{task.priority}</span><div className="task-copy"><strong>{task.title}</strong><span>{task.description||`Follow up with ${task.leadName}`}</span><small className={isOverdue?'overdue':''}>{task.dueAt?`${isOverdue?'Overdue · ':'Due '}${new Date(task.dueAt).toLocaleString()}`:'No due date'} · {task.assignee}</small></div><div className="task-actions">{task.leadId&&<button className="text-btn" onClick={()=>onOpenLead(task.leadId!)} aria-label={`Open ${task.leadName}`}>Open lead</button>}<button className="text-btn" onClick={()=>setEditing(task)}>Edit</button>{task.status==='Open'&&<button className="text-btn danger-text" onClick={async()=>{await onCancel(task.id);notify('Task cancelled')}}>Cancel</button>}</div></article>})}{!visible.length&&<div className="task-empty"><span>✓</span><h2>{view==='My queue'?'You’re all caught up':'No work in this view'}</h2><p>Change the filters or create a task for your team.</p></div>}</div>
    {(creating||editing)&&<TaskDialog task={editing} leads={leads} owners={owners} busy={busy} onClose={()=>{setCreating(false);setEditing(null)}} onSave={async draft=>{setBusy(true);try{if(editing)await onUpdate(editing.id,draft);else await onCreate(draft);notify(editing?'Task updated':'Task created');setCreating(false);setEditing(null)}finally{setBusy(false)}}}/>}</>
}

function TaskDialog({task,leads,owners,busy,onClose,onSave}:{task:WorkspaceTask|null;leads:WorkspaceLead[];owners:OwnerOption[];busy:boolean;onClose:()=>void;onSave:(draft:TaskDraft)=>Promise<void>}){
  const [draft,setDraft]=useState<TaskDraft>(task?{title:task.title,description:task.description,dueAt:task.dueAt,leadId:task.leadId,assigneeId:task.assigneeId,priority:task.priority}:emptyDraft)
  return <div className="modal-backdrop" onMouseDown={onClose}><form className="modal task-dialog" onMouseDown={event=>event.stopPropagation()} onSubmit={event=>{event.preventDefault();void onSave(draft)}}><div className="modal-head"><div><p className="eyebrow">{task?'Update assignment':'Plan client work'}</p><h2>{task?'Edit task':'Create task'}</h2></div><button type="button" className="close" onClick={onClose}>×</button></div><div className="task-form"><label>Task title<input autoFocus required minLength={3} maxLength={120} value={draft.title} onChange={event=>setDraft({...draft,title:event.target.value})}/></label><label className="wide">Brief / expected outcome<textarea value={draft.description} onChange={event=>setDraft({...draft,description:event.target.value})} placeholder="What does done look like?"/></label><label>Priority<select value={draft.priority} onChange={event=>setDraft({...draft,priority:event.target.value as TaskPriority})}>{priorities.map(value=><option key={value}>{value}</option>)}</select></label><label>Due date<input type="datetime-local" value={localInput(draft.dueAt)} onChange={event=>setDraft({...draft,dueAt:event.target.value?new Date(event.target.value).toISOString():null})}/></label><label>Related lead<select value={draft.leadId??''} onChange={event=>setDraft({...draft,leadId:event.target.value||null})}><option value="">General agency task</option>{leads.map(lead=><option key={lead.id} value={lead.id}>{lead.name} · {lead.company}</option>)}</select></label><label>Assignee<select value={draft.assigneeId??''} onChange={event=>setDraft({...draft,assigneeId:event.target.value||null})}><option value="">Unassigned</option>{owners.map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select></label></div><div className="modal-actions"><button type="button" className="btn secondary" onClick={onClose}>Cancel</button><button className="btn primary" disabled={busy||draft.title.trim().length<3}>{busy?'Saving…':task?'Save changes':'Create task'}</button></div></form></div>
}
