import {useCallback,useEffect,useState} from 'react'
import {inviteMember,listInvitations,listTeam,revokeInvitation,updateMemberRole} from '../../services/team'
import type {InvitationRow,MemberRole} from '../../types/database'
import type {OrganizationMember} from '../../services/organizations'

const roles:MemberRole[]=['OWNER','ADMIN','MANAGER','AGENT']
export function TeamPage({organizationId,currentRole,notify}:{organizationId:string;currentRole:string;notify:(message:string)=>void}){
  const [members,setMembers]=useState<OrganizationMember[]>([]),[invitations,setInvitations]=useState<InvitationRow[]>([]),[email,setEmail]=useState(''),[role,setRole]=useState<MemberRole>('AGENT'),[busy,setBusy]=useState(false)
  const refresh=useCallback(async()=>{const [nextMembers,nextInvites]=await Promise.all([listTeam(organizationId),listInvitations(organizationId)]);setMembers(nextMembers);setInvitations(nextInvites)},[organizationId])
  useEffect(()=>{void refresh()},[refresh])
  const canManage=currentRole==='OWNER'||currentRole==='ADMIN'
  const invite=async()=>{setBusy(true);try{await inviteMember(organizationId,email,role);setEmail('');await refresh();notify('Invitation sent securely')}catch(reason){notify(reason instanceof Error?reason.message:'Invitation failed')}finally{setBusy(false)}}
  return <><div className="page-heading"><div><p className="eyebrow">Access control</p><h1>Team</h1><p className="subheading">Invite teammates and keep permissions aligned with their responsibilities.</p></div></div>
    {canManage&&<div className="card team-invite"><div><h2>Invite a teammate</h2><p>A secure, seven-day invitation link will be emailed to them.</p></div><input aria-label="Invite email" type="email" placeholder="teammate@company.com" value={email} onChange={event=>setEmail(event.target.value)}/><select aria-label="Invite role" value={role} onChange={event=>setRole(event.target.value as MemberRole)}>{roles.filter(value=>currentRole==='OWNER'||value!=='OWNER').map(value=><option key={value}>{value}</option>)}</select><button className="btn primary" disabled={busy||!email} onClick={()=>void invite()}>{busy?'Sending…':'Send invitation'}</button></div>}
    <div className="card team-list"><div className="card-head"><div><h2>Workspace members</h2><p>{members.length} active member{members.length===1?'':'s'}</p></div></div>{members.map(member=><div className="team-row" key={member.userId}><span className="lead-avatar">{member.name.split(' ').map(value=>value[0]).join('').slice(0,2)}</span><div><strong>{member.name}</strong><small>Active workspace member</small></div>{canManage?<select aria-label={`Role for ${member.name}`} value={member.role} onChange={async event=>{try{await updateMemberRole(organizationId,member.userId,event.target.value as MemberRole);await refresh();notify('Member role updated')}catch(reason){notify(reason instanceof Error?reason.message:'Role update failed')}}}>{roles.filter(value=>currentRole==='OWNER'||value!=='OWNER').map(value=><option key={value}>{value}</option>)}</select>:<span className="role-pill">{member.role}</span>}</div>)}
      {invitations.length>0&&<><div className="card-head pending-head"><div><h2>Pending invitations</h2><p>Waiting to be accepted</p></div></div>{invitations.map(invitation=><div className="team-row" key={invitation.id}><span className="lead-avatar muted">✉</span><div><strong>{invitation.email}</strong><small>Expires {new Date(invitation.expires_at).toLocaleDateString()}</small></div><span className="role-pill">{invitation.role}</span><button className="text-btn danger-text" onClick={async()=>{await revokeInvitation(organizationId,invitation.id);await refresh();notify('Invitation revoked')}}>Revoke</button></div>)}</>}
    </div></>
}
