import { lazy, Suspense, useEffect, useRef, useState } from 'react'
import type { ReactNode } from 'react'
import { AssistantDemo, AutomationDemo, CRMDemo, DemoShell, HeroDemo, InboxDemo, PipelineDemo, TransformationStory } from './Demos'
import { demoLeads, faqs, industries, journey } from './content'
import { useLandingMotion } from './motion'
import './landing.css'

const AnalyticsDemo = lazy(()=>import('../Analytics').then(module=>({default:module.Analytics})))
type Props = { onLaunch:()=>void; onStart:()=>void; onDemo:()=>void }
const links=[['Product','product'],['Solutions','solutions'],['How it works','how-it-works'],['Pricing','pricing'],['Resources','resources']]

function SectionHeading({number,title,copy}:{number:string;title:ReactNode;copy:string}){
  return <header className="lf-section-heading" data-enter><p className="lf-kicker">{number}</p><h2>{title}</h2><p>{copy}</p></header>
}
function Brand(){return <a className="lf-brand" href="#top" aria-label="Nexara LeadFlow home"><span>N</span><strong>LeadFlow<small>by Nexara</small></strong></a>}

export default function LandingPage({onLaunch,onStart,onDemo}:Props){
  const root=useLandingMotion()
  const [menu,setMenu]=useState(false),[compact,setCompact]=useState(false)
  const [dialog,setDialog]=useState<string|null>(null)
  const menuButton=useRef<HTMLButtonElement>(null), sentinel=useRef<HTMLDivElement>(null)
  useEffect(()=>{
    const observer=new IntersectionObserver(([entry])=>setCompact(!entry.isIntersecting))
    if(sentinel.current)observer.observe(sentinel.current)
    return()=>observer.disconnect()
  },[])
  useEffect(()=>{
    if(!menu)return
    const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){setMenu(false);menuButton.current?.focus()}}
    document.addEventListener('keydown',key)
    return()=>document.removeEventListener('keydown',key)
  },[menu])
  return <div className="lf-site" ref={root} id="top">
    <a className="lf-skip" href="#lf-main">Skip to content</a><div ref={sentinel} className="lf-nav-sentinel"/>
    <header className={'lf-nav '+(compact?'lf-nav-compact':'')}><div className="lf-nav-inner"><Brand/><nav className="lf-desktop-links" aria-label="Main navigation">{links.map(([name,id])=><a key={id} href={'#'+id}>{name}</a>)}</nav><div className="lf-nav-actions"><button className="lf-text-button" onClick={onLaunch}>Sign in</button><button className="lf-button lf-small" onClick={onStart}>Get started <span>↗</span></button><button ref={menuButton} className="lf-menu-button" aria-expanded={menu} aria-controls="lf-mobile-menu" onClick={()=>setMenu(!menu)} aria-label={menu?'Close menu':'Open menu'}>{menu?'×':'☰'}</button></div></div>
    <nav id="lf-mobile-menu" className="lf-mobile-menu" hidden={!menu} aria-label="Mobile navigation">{links.map(([name,id])=><a key={id} href={'#'+id} onClick={()=>setMenu(false)}>{name}<span>↗</span></a>)}<button onClick={onLaunch}>Sign in</button></nav></header>
    <main id="lf-main">
      <section className="lf-hero lf-container"><div className="lf-hero-copy"><p className="lf-kicker lf-hero-intro"><span className="lf-live-dot"/> From first hello to the next sale</p><h1>Turn conversations<br/>into <em>customers.</em></h1><p className="lf-hero-description">LeadFlow captures enquiries, qualifies prospects with AI, organizes every opportunity and automatically follows up — so your team can focus on closing.</p><div className="lf-hero-actions"><button className="lf-button" onClick={onStart}>Start free <span>↗</span></button><a className="lf-button lf-outline" href="#how-it-works">See how it works <span>↓</span></a></div><p className="lf-fine">Explore the free product preview. Live AI, channel delivery and billing are not active yet.</p></div><HeroDemo/></section>

      <section className="lf-channel-section" aria-labelledby="channels-heading"><div className="lf-container"><p className="lf-kicker" id="channels-heading">Every enquiry. One intelligent sales system.</p><div className="lf-channel-flow" data-enter><div className="lf-channel-inputs">{['WhatsApp','Website','Instagram','Facebook','Ads','Referrals','Email'].map(c=><span key={c}>{c}</span>)}</div><span className="lf-flow-arrow" aria-hidden="true">→</span><div className="lf-flow-center"><span>N</span>LeadFlow</div><span className="lf-flow-arrow" aria-hidden="true">→</span><div className="lf-channel-outputs">{['Qualified leads','Follow-ups','Sales pipeline','Analytics'].map(c=><span key={c}>✓ {c}</span>)}</div></div><p className="lf-fine">The channel map shows the product direction. <a href="#integrations">See current integration readiness →</a></p></div></section>

      <TransformationStory/>
      <section id="ai-assistant" className="lf-tinted"><div className="lf-section"><SectionHeading number="02 / Knowledge before answers" title={<>An AI assistant that actually<br/>knows your business.</>} copy="Give your assistant the products, services, FAQs and policies your team trusts. Define the questions it asks, the tone it uses, when it’s available and when a person should step in."/><AssistantDemo/><div className="lf-under-demo"><p><strong>Grounded in your information.</strong> If a verified answer is missing, the right next step is clarification or a person.</p><p><strong>Configured around your process.</strong> Change qualification fields as your products, customers and sales process change.</p></div></div></section>

      <section id="crm" className="lf-section"><SectionHeading number="03 / A shared view of every opportunity" title={<>Every opportunity,<br/>finally organized.</>} copy="Keep the customer, requirements, source, status and owner together. A salesperson can open a record and understand the conversation without piecing it together from screenshots."/><div data-enter><CRMDemo/></div><p className="lf-fine lf-centered">The demo uses the same lead fields and status language as the LeadFlow workspace.</p></section>
      <section id="pipeline" className="lf-section lf-pipeline-section"><div className="lf-split-heading" data-enter><div><p className="lf-kicker">04 / Momentum you can see</p><h2>See every deal<br/>moving forward.</h2></div><p>Which prospects need attention? Who owns the next action? Where do deals stop moving? A shared pipeline gives the team the same picture.</p></div><PipelineDemo/></section>

      <section id="automations" className="lf-dark-section"><div className="lf-section"><SectionHeading number="05 / The follow-up that would have been missed" title={<>Follow-up happens<br/>even when you forget.</>} copy="Set a trigger, check the conditions and choose the next action. This example shows how a timed follow-up can bring a quiet conversation back to life."/><AutomationDemo/><p className="lf-closing-line" data-enter>No opportunity quietly disappears.</p><p className="lf-fine lf-centered">A guided workflow demonstration. Production scheduling and outbound messaging still need to be connected.</p></div></section>

      <section id="inbox" className="lf-section"><SectionHeading number="06 / Context that stays with the customer" title={<>One inbox.<br/>Every conversation.</>} copy="Switch channels without losing the thread. Let AI handle the repeatable questions, then bring a human into the conversation with the details already in place."/><InboxDemo/><div className="lf-team-handoff" data-enter><div><span>✦ AI takes the first pass</span><p>FAQs · Initial response · Qualification · Basic follow-up</p></div><b aria-hidden="true">→</b><div><span>Your team takes it further</span><p>Complex questions · Relationships · Negotiation · Closing</p></div></div><h3 className="lf-centered">AI when you need scale. Humans when customers need people.</h3></section>

      <section id="analytics" className="lf-tinted"><div className="lf-section"><SectionHeading number="07 / From activity to a clearer decision" title={<>Know what’s actually<br/>generating revenue.</>} copy="Start with where enquiries come from. Follow how many qualify and which become customers. Use the evidence to decide where your team should spend its time."/><AnalyticsStory/><p className="lf-fine lf-centered">Illustrative demo records. Revenue reporting requires recorded deal values; response-time and date trends require timestamped history.</p></div></section>

      <section id="how-it-works" className="lf-section"><SectionHeading number="08 / The whole picture" title={<>One system from first message<br/>to closed customer.</>} copy="Follow an opportunity through the workflow. Select or focus a stage to see what happens there."/><JourneyMap/><div className="lf-setup-path">{[['01','Connect','Choose where enquiries enter.'],['02','Teach','Add approved business knowledge.'],['03','Qualify','Ask the questions that establish fit.'],['04','Organize','Create a structured lead record.'],['05','Automate','Set the next action and owner.'],['06','Close','Give your team room to sell.']].map(([n,title,copy])=><div key={n}><span>{n}</span><h3>{title}</h3><p>{copy}</p></div>)}</div></section>
      <section id="solutions" className="lf-sand"><div className="lf-section"><SectionHeading number="09 / Your business, your questions" title={<>Built around how<br/>your business sells.</>} copy="A property viewing and a freight quote need different information. The workflow stays clear while the questions adapt to the business."/><IndustrySelector/></div></section>
      <section className="lf-section lf-before-after"><SectionHeading number="A better working day" title="Less chasing. More clarity." copy="The goal is a simpler handover: every conversation has context, every lead has an owner, and every follow-up has a place."/><Comparison/></section>

      <section id="integrations" className="lf-tinted"><div className="lf-section"><SectionHeading number="Channel readiness" title="Meet customers where they already are." copy="Explore the workflow today. Connect production channels as the integrations become available."/><div className="lf-integration-list">{[['WhatsApp','Official Cloud API groundwork exists. Live inbound and outbound delivery is pending.','In development'],['Website','Form capture and an embeddable conversation widget are planned.','Planned'],['Email','Shared email conversations are demonstrated here. Mailbox connection is not active.','Planned'],['API / Webhooks','Custom lead-source endpoints and authenticated ingestion are planned.','Planned']].map(([title,copy,state])=><article key={title}><h3>{title}</h3><p>{copy}</p><span>{state}</span></article>)}</div><p className="lf-fine">Available now: this interactive preview and the local demo workspace. Instagram, Facebook and ad integrations are future channels.</p></div></section>
      <section id="security" className="lf-section lf-security"><div><p className="lf-kicker">Trust begins with being clear</p><h2>Customer context<br/>deserves care.</h2></div><div><p>The project includes Supabase authentication services, tenant identifiers, database policy migrations and a server-side credential design.</p><p>Production tenant isolation, role enforcement and external integrations still require deployment and verification before handling live customer data. The demos on this page stay in your browser and use fictional records.</p><a href="#resources">Read the product questions →</a></div></section>
      <Pricing onStart={onStart}/>
      <section id="resources" className="lf-section lf-faq"><div className="lf-faq-intro"><p className="lf-kicker">A few things you may be wondering</p><h2>Good questions.<br/>Clear answers.</h2><p>What the product does, how the workflow fits together, and where this preview stands.</p></div><div>{faqs.map(([q,a],i)=><Accordion key={q} question={q} answer={a} index={i}/>)}</div></section>
      <section className="lf-final"><div className="lf-section"><span className="lf-final-message" data-enter>“Can we book a viewing?” <span>→ Qualified lead</span></span><h2>Every missed follow-up<br/>could be a missed customer.</h2><p>Bring your conversations, leads and sales workflow into one intelligent system.</p><div className="lf-hero-actions"><button className="lf-button" onClick={onStart}>Start free ↗</button><button className="lf-button lf-outline" onClick={()=>setDialog('Book a demo')}>Book a demo</button></div><p className="lf-fine">Free preview · no payment taken.</p></div></section>
    </main>
    <footer className="lf-footer lf-container"><div><Brand/><p>Turn conversations into customers.</p><small>© {new Date().getFullYear()} Nexara LeadFlow</small></div><div><h3>Product</h3>{[['Features','product'],['AI Assistant','ai-assistant'],['Automations','automations'],['Pipeline','pipeline'],['Analytics','analytics'],['Integrations','integrations']].map(([title,id])=><a href={'#'+id} key={id}>{title}</a>)}</div><div><h3>Solutions</h3>{['Real Estate','Automotive','Logistics','Education','Professional Services'].map(title=><a href="#solutions" key={title}>{title}</a>)}</div><div><h3>Resources</h3><a href="#resources">Help & FAQ</a><a href="#how-it-works">Product guide</a><a href="#security">Security & readiness</a><button onClick={onDemo}>Open demo workspace</button></div><div><h3>Company</h3>{['About','Contact','Privacy','Terms'].map(title=><button key={title} onClick={()=>setDialog(title)}>{title}</button>)}</div></footer>
    {dialog&&<InfoDialog title={dialog} close={()=>setDialog(null)} onDemo={onDemo}/>}
  </div>
}

function AnalyticsStory(){
  const [expanded,setExpanded]=useState(false)
  return <><DemoShell title="Analytics / Demo pipeline"><div className="lf-analytics-preview" data-enter><div className="lf-metrics">{[['Leads','4'],['Qualified or later','3'],['Won','1'],['Lead-to-win','25%'],['Response time','No history']].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><div className="lf-chart-grid"><div><p className="lf-pane-title">Pipeline distribution</p><div className="lf-demo-bars">{['New','Qualified','Contacted','Won'].map((label,i)=><div key={label}><span style={{'--i':i} as React.CSSProperties}/><strong>1</strong><small>{label}</small></div>)}</div></div><div className="lf-demo-funnel"><p className="lf-pane-title">Conversion snapshot</p>{[['All leads',4],['Qualified or later',3],['Won',1]].map(([label,n])=><div key={label}><span>{label}</span><strong>{n}</strong><i style={{transform:`scaleX(${Number(n)/4})`}}/></div>)}<p className="lf-fine">Website, WhatsApp, referral and email: one demo lead each.</p></div></div></div></DemoShell><button className="lf-button lf-outline lf-report-toggle" aria-expanded={expanded} onClick={()=>setExpanded(!expanded)}>{expanded?'Close interactive report':'Try the actual analytics tools'} ↗</button>{expanded&&<div className="lf-live-report"><Suspense fallback={<p role="status">Loading analytics…</p>}><AnalyticsDemo leads={demoLeads}/></Suspense></div>}</>
}
function JourneyMap(){
  const [active,setActive]=useState(0)
  return <div className="lf-journey"><div className="lf-journey-stages">{journey.map(([title],i)=><button key={title} aria-pressed={active===i} onMouseEnter={()=>setActive(i)} onFocus={()=>setActive(i)} onClick={()=>setActive(i)}><span>{String(i+1).padStart(2,'0')}</span>{title}</button>)}</div><div className="lf-journey-detail"><span>0{active+1}</span><div><h3>{journey[active][0]}</h3><p>{journey[active][1]}</p></div></div></div>
}
function IndustrySelector(){
  const [industry,setIndustry]=useState<keyof typeof industries>('Real Estate')
  return <div className="lf-industries"><div className="lf-industry-options" aria-label="Choose an industry">{(Object.keys(industries) as (keyof typeof industries)[]).map(title=><button key={title} aria-pressed={industry===title} onClick={()=>setIndustry(title)}>{title}<span>↗</span></button>)}</div><div className="lf-industry-preview" key={industry}><p className="lf-kicker">Example workflow / {industry}</p><h3>The questions change.<br/>The next step stays clear.</h3><ol><li>New enquiry</li>{industries[industry].map(step=><li key={step}>{step}</li>)}</ol><p className="lf-fine">An example sales process, not a separate industry integration.</p></div></div>
}
function Comparison(){
  const [after,setAfter]=useState(true)
  return <div className="lf-comparison"><div className="lf-comparison-switch" aria-label="Compare workflows"><button aria-pressed={!after} onClick={()=>setAfter(false)}>Before LeadFlow</button><button aria-pressed={after} onClick={()=>setAfter(true)}>With LeadFlow</button></div><div className={'lf-comparison-list '+(after?'is-after':'')}>{(after?['Unified inbox','Prompt initial response','Structured qualification','Rule-based follow-up','Assigned ownership','Measurable pipeline']:['Scattered messages','Slow responses','Manual qualification','Forgotten follow-ups','No clear ownership','Poor visibility']).map((text,i)=><p key={text}><span>{after?'✓':'—'}</span><small>0{i+1}</small>{text}</p>)}</div><p className="lf-fine">The intended workflow improvement, demonstrated with sample data.</p></div>
}
function Pricing({onStart}:{onStart:()=>void}){
  return <section id="pricing" className="lf-tinted"><div className="lf-section"><SectionHeading number="Choose your next stage" title="Room to start. Room to grow." copy="Proposed monthly plans in Kenyan shillings. Explore the free preview today; paid subscriptions and final entitlements will be confirmed before launch."/><div className="lf-pricing-grid">{[['Starter','3,000','Get your enquiries organized.','2 members','100 leads / month','3 automations'],['Growth','7,500','Build a repeatable sales process.','5 members','500 leads / month','15 automations'],['Pro','15,000','Coordinate a larger sales team.','25 members','5,000 leads / month','100 automations']].map(([name,price,copy,...features],i)=><article className={i===1?'lf-price lf-featured':'lf-price'} key={name} data-enter>{i===1&&<span className="lf-plan-note">For growing teams</span>}<h3>{name}</h3><p>{copy}</p><div className="lf-price-value">KSh {price}<small>/ month</small></div><button className={'lf-button '+(i!==1?'lf-outline':'')} onClick={onStart}>Explore {name} ↗</button><ul>{features.map(f=><li key={f}>✓ {f}</li>)}<li>✓ Shared CRM & pipeline</li></ul></article>)}</div><p className="lf-fine lf-centered">Implementation scope and setup costs will be agreed separately. Annual billing is not available in this preview.</p></div></section>
}
function Accordion({question,answer,index}:{question:string;answer:string;index:number}){
  const [open,setOpen]=useState(false)
  return <article className={'lf-accordion '+(open?'is-open':'')}><h3><button id={'lf-faq-q-'+index} aria-expanded={open} aria-controls={'lf-faq-a-'+index} onClick={()=>setOpen(!open)}>{question}<span aria-hidden="true">{open?'−':'+'}</span></button></h3><div className="lf-accordion-answer" id={'lf-faq-a-'+index} role="region" aria-labelledby={'lf-faq-q-'+index} hidden={!open}><p>{answer}</p></div></article>
}
function InfoDialog({title,close,onDemo}:{title:string;close:()=>void;onDemo:()=>void}){
  const ref=useRef<HTMLDialogElement>(null)
  const opener=useRef(document.activeElement as HTMLElement|null)
  useEffect(()=>{const el=ref.current;el?.showModal();return()=>{el?.close();opener.current?.focus()}},[])
  const text:Record<string,string>={
    About:'Nexara LeadFlow is being built for SMEs that need a clearer path from an enquiry to a customer. The first demonstration focuses on a fictional Kenyan real-estate business. Explore the product story and the local workspace to see the current experience.',
    Contact:'A public support address and sales booking channel have not been published yet. You can explore the self-guided demo now. No contact request is collected or submitted by this preview.',
    'Book a demo':'Live appointment booking is not available yet. The self-guided workspace is ready to explore, with fictional leads, pipeline stages and analytics. No booking is created by opening the demo.',
    Privacy:'Draft for legal review before launch. The interactive scenes on this page run in browser memory and do not submit your questions or demo actions to an AI provider. Account forms use the configured authentication service when available. Production retention periods, data controller details and privacy contact information must be finalized before collecting live customer data.',
    Terms:'Draft for legal review before launch. This site is a product preview. Demonstrated AI replies, channel activity and workflow execution are simulations. Prices are proposed; no subscription or payment is created here. Final service terms, cancellation terms and support commitments must be published before paid service begins.',
  }
  return <dialog ref={ref} className="lf-info-dialog" onCancel={close} onClick={e=>{if(e.target===e.currentTarget)close()}}><div><button className="lf-dialog-close" onClick={close} aria-label="Close dialog">×</button><p className="lf-kicker">Nexara LeadFlow</p><h2>{title}</h2><p>{text[title]}</p><button className="lf-button" onClick={onDemo}>Explore the demo ↗</button></div></dialog>
}
