import { useMemo, useRef, useState } from 'react'
import type { FormEvent } from 'react'
import { leadStages } from './types'
import type { ContactDraft, LeadDraft, LeadStage, OwnerOption, WorkspaceContact, WorkspaceLead } from './types'
import './crm.css'

type Notify=(message:string)=>void
const sources=['Manual','Website','WhatsApp','Referral','Email']
const blankLead:LeadDraft={name:'',email:'',phone:'',company:'',interest:'',source:'Manual',stage:'New',score:40,value:'Not set',owner:'Unassigned',ownerId:null,tags:[],nextAction:'Make first contact'}
const initials=(name:string)=>name.split(' ').map(part=>part[0]).join('').slice(0,2).toUpperCase()

export function LeadDialog({lead,owners,onClose,onSave}:{lead?:WorkspaceLead;owners:OwnerOption[];onClose:()=>void;onSave:(draft:LeadDraft)=>Promise<void>}){
  const dialog=useRef<HTMLDialogElement>(null)
  const [draft,setDraft]=useState<LeadDraft>(lead??blankLead)
  const set=<K extends keyof LeadDraft>(key:K,value:LeadDraft[K])=>setDraft(current=>({...current,[key]:value}))
  const [saving,setSaving]=useState(false)
  const submit=async(event:FormEvent)=>{event.preventDefault();setSaving(true);try{await onSave({...draft,name:draft.name.trim(),interest:draft.interest.trim(),email:draft.email.trim(),phone:draft.phone.trim(),tags:draft.tags.filter(Boolean)});onClose()}finally{setSaving(false)}}
  return <dialog ref={el=>{dialog.current=el;if(el&&!el.open)el.showModal()}} className="crm-dialog" aria-labelledby="lead-dialog-title" onCancel={onClose} onClick={event=>event.target===event.currentTarget&&onClose()}><form onSubmit={submit}>
    <div className="modal-head"><div><p className="eyebrow">{lead?'Edit record':'Quick create'}</p><h2 id="lead-dialog-title">{lead?'Update lead':'Add a lead'}</h2></div><button type="button" className="close" onClick={onClose} aria-label="Close">×</button></div>
    <div className="crm-form-grid"><label>Full name<input value={draft.name} onChange={e=>set('name',e.target.value)} required autoFocus/></label><label>Interest<input value={draft.interest} onChange={e=>set('interest',e.target.value)} required/></label><label>Email<input type="email" value={draft.email} onChange={e=>set('email',e.target.value)}/></label><label>Phone<input value={draft.phone} onChange={e=>set('phone',e.target.value)}/></label><label>Company<input value={draft.company} onChange={e=>set('company',e.target.value)}/></label><label>Budget / value<input value={draft.value} onChange={e=>set('value',e.target.value)}/></label><label>Source<select value={draft.source} onChange={e=>set('source',e.target.value)}>{sources.map(source=><option key={source}>{source}</option>)}</select></label><label>Owner<select value={draft.ownerId??''} onChange={e=>{const selected=owners.find(owner=>owner.id===e.target.value);setDraft(current=>({...current,ownerId:selected?.id??null,owner:selected?.label??'Unassigned'}))}}><option value="">Unassigned</option>{owners.map(owner=><option key={owner.id} value={owner.id}>{owner.label}</option>)}</select></label><label>Stage<select value={draft.stage} onChange={e=>set('stage',e.target.value as LeadStage)}>{leadStages.map(stage=><option key={stage}>{stage}</option>)}</select></label><label>Lead score<input type="number" min="0" max="100" value={draft.score} onChange={e=>set('score',Number(e.target.value))}/></label><label className="wide">Next action<input value={draft.nextAction} onChange={e=>set('nextAction',e.target.value)}/></label><label className="wide">Tags <span>comma separated</span><input value={draft.tags.join(', ')} onChange={e=>set('tags',e.target.value.split(',').map(tag=>tag.trim()))}/></label></div>
    <div className="modal-actions"><button type="button" className="btn secondary" onClick={onClose}>Cancel</button><button className="btn primary" disabled={saving}>{saving?'Saving…':lead?'Save changes':'Create lead'}</button></div>
  </form></dialog>
}

export function LeadsPage({leads,owners,isDemo,onAdd,onUpdate,onArchive,onOpen,notify}:{leads:WorkspaceLead[];owners:OwnerOption[];isDemo:boolean;onAdd:()=>void;onUpdate:(id:string,changes:Partial<WorkspaceLead>,event?:string)=>void|Promise<unknown>;onArchive:(ids:string[])=>void|Promise<unknown>;onOpen:(id:string)=>void;notify:Notify}){
  const [query,setQuery]=useState(''),[stage,setStage]=useState('All'),[owner,setOwner]=useState('All'),[sort,setSort]=useState('score'),[selected,setSelected]=useState<string[]>([])
  const filtered=useMemo(()=>leads.filter(lead=>(stage==='All'||lead.stage===stage)&&(owner==='All'||lead.owner===owner)&&[lead.name,lead.interest,lead.email,lead.phone,lead.source,...lead.tags].join(' ').toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):sort==='recent'?b.createdAt.localeCompare(a.createdAt):b.score-a.score),[leads,owner,query,sort,stage])
  const allSelected=filtered.length>0&&filtered.every(lead=>selected.includes(lead.id))
  const bulk=async(action:'assign'|'qualified'|'archive')=>{if(!selected.length)return;const firstOwner=owners[0];if(action==='assign'&&firstOwner)await Promise.all(selected.map(id=>onUpdate(id,{owner:firstOwner.label,ownerId:firstOwner.id},`Assigned to ${firstOwner.label}`)));if(action==='qualified')await Promise.all(selected.map(id=>onUpdate(id,{stage:'Qualified'},'Stage changed to Qualified')));if(action==='archive')await onArchive(selected);notify(`${selected.length} lead${selected.length===1?'':'s'} updated`);setSelected([])}
  return <><div className="page-heading"><div><p className="eyebrow">CRM · {leads.length} active records</p><h1>Leads</h1><p className="subheading">Search, qualify, assign and move every opportunity.</p></div><button className="btn primary" onClick={onAdd}>＋ Add lead</button></div>
    <div className="crm-toolbar"><label className="table-search">⌕ <input aria-label="Search leads" placeholder="Search name, interest, tag…" value={query} onChange={e=>setQuery(e.target.value)}/></label><label>Stage<select aria-label="Filter by stage" value={stage} onChange={e=>setStage(e.target.value)}><option>All</option>{leadStages.map(value=><option key={value}>{value}</option>)}</select></label><label>Owner<select aria-label="Filter by owner" value={owner} onChange={e=>setOwner(e.target.value)}><option>All</option><option>Unassigned</option>{owners.map(value=><option key={value.id}>{value.label}</option>)}</select></label><label>Sort<select aria-label="Sort leads" value={sort} onChange={e=>setSort(e.target.value)}><option value="score">Highest score</option><option value="recent">Newest</option><option value="name">Name A–Z</option></select></label><button className="btn secondary" onClick={()=>{setQuery('');setStage('All');setOwner('All')}}>Reset</button></div>
    {selected.length>0&&<div className="bulk-bar"><strong>{selected.length} selected</strong><button onClick={()=>bulk('assign')}>Assign to me</button><button onClick={()=>bulk('qualified')}>Mark qualified</button><button className="danger-text" onClick={()=>bulk('archive')}>Archive</button><button onClick={()=>setSelected([])}>Clear</button></div>}
    <div className="card table-card full-table crm-leads-table"><div className="table-wrap"><table><thead><tr><th><input aria-label="Select all visible leads" type="checkbox" checked={allSelected} onChange={()=>setSelected(allSelected?selected.filter(id=>!filtered.some(lead=>lead.id===id)):[...new Set([...selected,...filtered.map(lead=>lead.id)])])}/></th><th>Lead</th><th>Interest</th><th>Source</th><th>Value</th><th>Owner</th><th>Stage</th><th>Score</th><th>Last activity</th></tr></thead><tbody>{filtered.map(lead=><tr key={lead.id}><td><input aria-label={`Select ${lead.name}`} type="checkbox" checked={selected.includes(lead.id)} onChange={()=>setSelected(current=>current.includes(lead.id)?current.filter(id=>id!==lead.id):[...current,lead.id])}/></td><td><button className="lead-link" onClick={()=>onOpen(lead.id)}><span className="lead-avatar">{initials(lead.name)}</span><span><strong>{lead.name}</strong><small>{lead.email||lead.phone||'No contact details'}</small></span></button></td><td>{lead.interest}</td><td>{lead.source}</td><td>{lead.value}</td><td><select aria-label={`Owner for ${lead.name}`} value={lead.ownerId??''} onChange={e=>{const selectedOwner=owners.find(owner=>owner.id===e.target.value);void onUpdate(lead.id,{owner:selectedOwner?.label??'Unassigned',ownerId:selectedOwner?.id??null},`Assigned to ${selectedOwner?.label??'Unassigned'}`)}}><option value="">Unassigned</option>{owners.map(value=><option key={value.id} value={value.id}>{value.label}</option>)}</select></td><td><select aria-label={`Stage for ${lead.name}`} value={lead.stage} onChange={e=>void onUpdate(lead.id,{stage:e.target.value as LeadStage},`Stage changed to ${e.target.value}`)}>{leadStages.map(value=><option key={value}>{value}</option>)}</select></td><td><span className={lead.score>75?'score high':'score'}>{lead.score}</span></td><td>{lead.lastActivity}</td></tr>)}</tbody></table>{!filtered.length&&<div className="crm-empty"><strong>No matching leads</strong><p>Change the filters or create a new opportunity.</p><button className="btn primary" onClick={onAdd}>Add lead</button></div>}</div></div>
    <p className="data-note">{isDemo?'Demo mode · changes are saved only in this browser.':'Live workspace · changes are securely synced through Supabase.'}</p></>
}

export function LeadProfile({lead,owners,onClose,onUpdate,onAddNote,onSchedule,onEdit,notify}:{lead:WorkspaceLead;owners:OwnerOption[];onClose:()=>void;onUpdate:(id:string,changes:Partial<WorkspaceLead>,event?:string)=>void|Promise<unknown>;onAddNote:(id:string,text:string)=>void|Promise<unknown>;onSchedule:(id:string,dueAt:string)=>void|Promise<unknown>;onEdit:()=>void;notify:Notify}){
  const [note,setNote]=useState(''),[followUp,setFollowUp]=useState('')
  return <dialog ref={el=>{if(el&&!el.open)el.showModal()}} className="lead-profile-dialog" aria-labelledby="lead-profile-title" onCancel={onClose} onClick={e=>e.target===e.currentTarget&&onClose()}><div className="lead-profile">
    <header><div className="lead-profile-title"><span className="large-avatar">{initials(lead.name)}</span><div><p className="eyebrow">Lead profile</p><h2 id="lead-profile-title">{lead.name}</h2><p>{lead.company||'No company'} · {lead.source}</p></div></div><div><button className="btn secondary" onClick={onEdit}>Edit</button><button className="close" onClick={onClose} aria-label="Close profile">×</button></div></header>
    <div className="lead-profile-body"><main><section className="profile-summary"><div><small>STATUS</small><select value={lead.stage} onChange={e=>void onUpdate(lead.id,{stage:e.target.value as LeadStage},`Stage changed to ${e.target.value}`)}>{leadStages.map(stage=><option key={stage}>{stage}</option>)}</select></div><div><small>SCORE</small><strong>{lead.score}/100</strong></div><div><small>OWNER</small><select value={lead.ownerId??''} onChange={e=>{const selected=owners.find(owner=>owner.id===e.target.value);void onUpdate(lead.id,{owner:selected?.label??'Unassigned',ownerId:selected?.id??null},`Assigned to ${selected?.label??'Unassigned'}`)}}><option value="">Unassigned</option>{owners.map(owner=><option key={owner.id} value={owner.id}>{owner.label}</option>)}</select></div><div><small>VALUE</small><strong>{lead.value}</strong></div></section>
      <section className="profile-card"><h3>Opportunity summary</h3><p><strong>{lead.interest}</strong></p><dl><div><dt>Next action</dt><dd>{lead.nextAction}</dd></div><div><dt>Created</dt><dd>{new Date(lead.createdAt).toLocaleDateString()}</dd></div><div><dt>Email</dt><dd>{lead.email||'Not provided'}</dd></div><div><dt>Phone</dt><dd>{lead.phone||'Not provided'}</dd></div></dl><div className="profile-tags">{lead.tags.map(tag=><span key={tag}>{tag}</span>)}</div></section>
      <section className="profile-card"><div className="section-title"><h3>Activity timeline</h3><span>{lead.notes.length} events</span></div><form className="note-form" onSubmit={async e=>{e.preventDefault();if(!note.trim())return;await onAddNote(lead.id,note.trim());setNote('');notify('Note added')}}><input aria-label="Add note" value={note} onChange={e=>setNote(e.target.value)} placeholder="Add an internal note…"/><button className="btn primary">Add note</button></form><ol className="timeline">{[...lead.notes].reverse().map(event=><li key={event.id}><span className={'timeline-icon '+event.kind}>{event.kind==='note'?'✎':event.kind==='follow-up'?'◷':'✓'}</span><div><strong>{event.text}</strong><time>{new Date(event.at).toLocaleString()}</time></div></li>)}</ol></section>
    </main><aside><section className="profile-card"><h3>Schedule follow-up</h3><p>Record a follow-up task in this lead timeline.</p><input aria-label="Follow-up date" type="datetime-local" value={followUp} onChange={e=>setFollowUp(e.target.value)}/><button className="btn primary" disabled={!followUp} onClick={async()=>{await onSchedule(lead.id,new Date(followUp).toISOString());setFollowUp('');notify('Follow-up scheduled')}}>Schedule</button></section><section className="profile-card"><h3>AI summary</h3><p className="ai-summary">James-style summaries will be generated from real conversation history once the AI provider is configured. For now, this panel uses structured lead fields only.</p><strong>{lead.interest}</strong><p>Score {lead.score}; currently {lead.stage.toLowerCase()}; next action: {lead.nextAction.toLowerCase()}.</p></section></aside></div>
  </div></dialog>
}

export function PipelinePage({leads,isDemo,onMove,onOpen,notify}:{leads:WorkspaceLead[];isDemo:boolean;onMove:(id:string,stage:LeadStage)=>void|Promise<unknown>;onOpen:(id:string)=>void;notify:Notify}){
  const [dragging,setDragging]=useState<string|null>(null),[query,setQuery]=useState('')
  const visible=leads.filter(lead=>lead.name.toLowerCase().includes(query.toLowerCase())||lead.interest.toLowerCase().includes(query.toLowerCase()))
  return <><div className="page-heading"><div><p className="eyebrow">Sales workspace</p><h1>Pipeline</h1><p className="subheading">Drag opportunities forward or use the stage control on mobile.</p></div><div className="pipeline-total"><span>Open opportunities</span><strong>{visible.filter(lead=>!['Won','Lost'].includes(lead.stage)).length}</strong></div></div><div className="pipeline-toolbar"><label className="table-search">⌕ <input aria-label="Search pipeline" placeholder="Find an opportunity" value={query} onChange={e=>setQuery(e.target.value)}/></label><span>{isDemo?'Demo changes persist in this browser':'Pipeline synced with your live workspace'}</span></div>
    <div className="pipeline-board crm-pipeline">{leadStages.map(stage=><section key={stage} aria-label={`${stage} stage`} className={'pipeline-column '+(dragging?'is-dragging':'')} onDragOver={e=>e.preventDefault()} onDrop={()=>{if(dragging){onMove(dragging,stage);notify(`Lead moved to ${stage}`);setDragging(null)}}}><header><span className={`stage-dot ${stage.toLowerCase()}`}/><strong>{stage}</strong><b>{visible.filter(lead=>lead.stage===stage).length}</b></header><div className="pipeline-cards">{visible.filter(lead=>lead.stage===stage).map(lead=><article draggable onDragStart={()=>setDragging(lead.id)} onDragEnd={()=>setDragging(null)} className="pipeline-card" key={lead.id}><button className="pipeline-card-main" onClick={()=>onOpen(lead.id)}><span className="lead-avatar">{initials(lead.name)}</span><strong>{lead.name}</strong><p>{lead.interest}</p><div className="pipeline-card-meta"><span>{lead.value}</span><span>{lead.score} score</span></div></button><div className="pipeline-card-foot"><span>{lead.owner}</span><select aria-label={`Move ${lead.name}`} value={lead.stage} onChange={e=>{onMove(lead.id,e.target.value as LeadStage);notify(`Lead moved to ${e.target.value}`)}}>{leadStages.map(value=><option key={value}>{value}</option>)}</select></div></article>)}{!visible.some(lead=>lead.stage===stage)&&<div className="pipeline-empty">Drop a lead here</div>}</div></section>)}</div></>
}

const blankContact:ContactDraft={name:'',email:'',phone:'',company:'',tags:[],type:'Prospect'}
export function ContactsPage({contacts,leads,onAdd,onUpdate,notify}:{contacts:WorkspaceContact[];leads:WorkspaceLead[];onAdd:(draft:ContactDraft)=>void|Promise<unknown>;onUpdate:(id:string,changes:Partial<WorkspaceContact>)=>void|Promise<unknown>;notify:Notify}){
  const [query,setQuery]=useState(''),[editing,setEditing]=useState<WorkspaceContact|null>(null),[creating,setCreating]=useState(false),[type,setType]=useState('All')
  const filtered=contacts.filter(contact=>(type==='All'||contact.type===type)&&[contact.name,contact.email,contact.phone,contact.company,...contact.tags].join(' ').toLowerCase().includes(query.toLowerCase()))
    return <><div className="page-heading"><div><p className="eyebrow">Customer directory</p><h1>Contacts</h1><p className="subheading">People, companies and their opportunity history.</p></div><button className="btn primary" onClick={()=>setCreating(true)}>＋ Add contact</button></div><div className="contact-summary"><div><strong>{contacts.length}</strong><span>Total contacts</span></div><div><strong>{contacts.filter(c=>c.type==='Lead').length}</strong><span>Active leads</span></div><div><strong>{contacts.filter(c=>c.type==='Customer').length}</strong><span>Customers</span></div><div><strong>{new Set(contacts.map(c=>c.company).filter(Boolean)).size}</strong><span>Companies</span></div></div><div className="crm-toolbar"><label className="table-search">⌕ <input aria-label="Search contacts" placeholder="Search contacts" value={query} onChange={e=>setQuery(e.target.value)}/></label><label>Type<select aria-label="Filter contacts by type" value={type} onChange={e=>setType(e.target.value)}><option>All</option><option>Lead</option><option>Prospect</option><option>Customer</option></select></label></div><div className="card table-card full-table contacts-table"><div className="table-wrap"><table><thead><tr><th>Contact</th><th>Company</th><th>Phone</th><th>Type</th><th>Tags</th><th>Lead history</th><th>Last activity</th></tr></thead><tbody>{filtered.map(contact=><tr key={contact.id} onClick={()=>setEditing(contact)}><td><div className="lead-cell"><span className="lead-avatar">{initials(contact.name)}</span><span><strong>{contact.name}</strong><small>{contact.email||'No email'}</small></span></div></td><td>{contact.company||'—'}</td><td>{contact.phone||'—'}</td><td><span className={`contact-type ${contact.type.toLowerCase()}`}>{contact.type}</span></td><td><div className="profile-tags">{contact.tags.slice(0,2).map(tag=><span key={tag}>{tag}</span>)}</div></td><td>{leads.filter(lead=>lead.email&&lead.email===contact.email).length}</td><td>{contact.lastActivity}</td></tr>)}</tbody></table>{!filtered.length&&<div className="crm-empty"><strong>No matching contacts</strong><p>Try a different search or type.</p></div>}</div></div>{(creating||editing)&&<ContactDialog contact={editing??undefined} onClose={()=>{setCreating(false);setEditing(null)}} onSave={async draft=>{if(editing)await onUpdate(editing.id,draft);else await onAdd(draft);notify(editing?'Contact updated':'Contact created')}}/>}</>
}

function ContactDialog({contact,onClose,onSave}:{contact?:WorkspaceContact;onClose:()=>void;onSave:(draft:ContactDraft)=>void|Promise<unknown>}){
  const [draft,setDraft]=useState<ContactDraft>(contact??blankContact)
  return <dialog ref={el=>{if(el&&!el.open)el.showModal()}} className="crm-dialog compact" aria-labelledby="contact-dialog-title" onCancel={onClose} onClick={e=>e.target===e.currentTarget&&onClose()}><form onSubmit={async e=>{e.preventDefault();await onSave(draft);onClose()}}><div className="modal-head"><div><p className="eyebrow">Customer directory</p><h2 id="contact-dialog-title">{contact?'Edit contact':'Add contact'}</h2></div><button type="button" className="close" onClick={onClose} aria-label="Close contact dialog">×</button></div><div className="crm-form-grid"><label>Full name<input autoFocus required value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Company<input value={draft.company} onChange={e=>setDraft({...draft,company:e.target.value})}/></label><label>Email<input type="email" value={draft.email} onChange={e=>setDraft({...draft,email:e.target.value})}/></label><label>Phone<input value={draft.phone} onChange={e=>setDraft({...draft,phone:e.target.value})}/></label><label>Type<select value={draft.type} onChange={e=>setDraft({...draft,type:e.target.value as ContactDraft['type']})}><option>Lead</option><option>Prospect</option><option>Customer</option></select></label><label>Tags<input value={draft.tags.join(', ')} onChange={e=>setDraft({...draft,tags:e.target.value.split(',').map(tag=>tag.trim()).filter(Boolean)})}/></label></div><div className="modal-actions"><button type="button" className="btn secondary" onClick={onClose}>Cancel</button><button className="btn primary">Save contact</button></div></form></dialog>
}
