import {useEffect,useState} from 'react'
import {requireSupabase} from '../../services/api'
import {updatePassword} from '../../services/auth'
import {saveOrganizationSettings,type OrganizationSettingsInput,type OrganizationSummary} from '../../services/organizations'
import {deleteWorkspace,exportWorkspace,getNotificationPreferences,saveNotificationPreferences} from '../../services/workspaceAdmin'
import type {NotificationPreferenceRow} from '../../types/database'

const fromOrganization=(organization:OrganizationSummary):OrganizationSettingsInput=>({name:organization.name,industry:organization.industry??'',website:organization.website??'',phone:organization.phone??'',country:organization.country??'KE',timezone:organization.timezone??'Africa/Nairobi'})
type Tab='Organization'|'Profile'|'Notifications'|'Security'|'Data & privacy'
export function SettingsPage({organization,userId,userEmail,onSaved,onProfileSaved,notify}:{organization:OrganizationSummary;userId:string;userEmail:string;onSaved:()=>Promise<void>;onProfileSaved:()=>Promise<void>;notify:(message:string)=>void}){
  const [tab,setTab]=useState<Tab>('Organization'),[form,setForm]=useState(()=>fromOrganization(organization)),[saving,setSaving]=useState(false),[saved,setSaved]=useState(false),[fullName,setFullName]=useState(''),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[confirmation,setConfirmation]=useState('')
  const [preferences,setPreferences]=useState<NotificationPreferenceRow>({organization_id:organization.id,user_id:userId,in_app:true,email_qualified_lead:true,email_assignment:true,email_follow_up:true,email_automation_failure:true,email_integration_failure:true,updated_at:new Date().toISOString()})
  const canManage=['OWNER','ADMIN'].includes(organization.role)
  useEffect(()=>{setForm(fromOrganization(organization));void requireSupabase().from('profiles').select('full_name,username').eq('id',userId).single().then(({data})=>{setFullName(data?.full_name??'');setUsername(data?.username??'')});void getNotificationPreferences(organization.id,userId).then(value=>value&&setPreferences(value))},[organization,userId])
  const set=<K extends keyof OrganizationSettingsInput>(key:K,value:OrganizationSettingsInput[K])=>{setSaved(false);setForm(current=>({...current,[key]:value}))}
  const saveOrganization=async()=>{setSaving(true);try{await saveOrganizationSettings(organization.id,form);await onSaved();setSaved(true);notify('Workspace settings saved')}catch(reason){notify(reason instanceof Error?reason.message:'Unable to save settings')}finally{setSaving(false)}}
  const saveProfile=async()=>{setSaving(true);try{const {error}=await requireSupabase().rpc('update_current_profile',{profile_full_name:fullName.trim(),profile_username:username.trim()});if(error)throw error;await onProfileSaved();notify('Profile and username saved')}catch(reason){notify(reason instanceof Error?reason.message:'Unable to save profile')}finally{setSaving(false)}}
  const savePreferences=async()=>{setSaving(true);try{setPreferences(await saveNotificationPreferences(preferences));notify('Notification preferences saved')}catch(reason){notify(reason instanceof Error?reason.message:'Unable to save preferences')}finally{setSaving(false)}}
  const download=async()=>{try{const data=await exportWorkspace(organization.id),url=URL.createObjectURL(new Blob([JSON.stringify({exportedAt:new Date().toISOString(),organization:form,data},null,2)],{type:'application/json'})),link=document.createElement('a');link.href=url;link.download=`${organization.name.toLowerCase().replaceAll(/[^a-z0-9]+/g,'-')}-export.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notify('Workspace export downloaded')}catch(reason){notify(reason instanceof Error?reason.message:'Unable to export workspace')}}
  const tabs:Tab[]=['Organization','Profile','Notifications','Security','Data & privacy']
  return <><div className="page-heading"><div><p className="eyebrow">Workspace administration</p><h1>Settings</h1><p className="subheading">Identity, alerts, security and data controls.</p></div>{tab==='Organization'&&canManage&&<button className="btn primary" disabled={saving} onClick={()=>void saveOrganization()}>{saving?'Saving…':'Save changes'}</button>}</div><div className="settings-layout"><aside className="card settings-nav">{tabs.map(value=><button key={value} className={tab===value?'active':''} onClick={()=>setTab(value)}>{value}</button>)}</aside><div className="settings-content">
  {tab==='Organization'&&<section className="card settings-card"><div className="settings-card-head"><div><h2>Organization details</h2><p>Used in assistant context, invitations and customer communication.</p></div>{saved&&<span className="saved-label">✓ Saved</span>}</div><div className="settings-form"><label>Business name<input disabled={!canManage} value={form.name} onChange={event=>set('name',event.target.value)}/></label><label>Industry<input disabled={!canManage} value={form.industry} onChange={event=>set('industry',event.target.value)}/></label><label>Website<input disabled={!canManage} type="url" value={form.website} onChange={event=>set('website',event.target.value)}/></label><label>Phone<input disabled={!canManage} value={form.phone} onChange={event=>set('phone',event.target.value)}/></label><label>Country<select disabled={!canManage} value={form.country} onChange={event=>set('country',event.target.value)}><option value="KE">Kenya</option><option value="UG">Uganda</option><option value="TZ">Tanzania</option><option value="RW">Rwanda</option><option value="OTHER">Other</option></select></label><label>Timezone<select disabled={!canManage} value={form.timezone} onChange={event=>set('timezone',event.target.value)}><option>Africa/Nairobi</option><option>Africa/Kampala</option><option>Africa/Dar_es_Salaam</option><option>Africa/Kigali</option><option>UTC</option></select></label></div></section>}
  {tab==='Profile'&&<section className="card settings-card"><h2>Your profile</h2><p>Your username appears in the overview greeting and workspace navigation. Your full name is shown to teammates and on assigned customer records.</p><div className="settings-form"><label>Username<input value={username} minLength={3} maxLength={32} pattern="[a-z0-9][a-z0-9._-]{2,31}" onChange={event=>setUsername(event.target.value.toLowerCase().replaceAll(/[^a-z0-9._-]/g,''))} placeholder="your.username"/><small>3–32 lowercase letters, numbers, dots, dashes or underscores.</small></label><label>Full name<input value={fullName} onChange={event=>setFullName(event.target.value)}/></label><label>Email<input disabled value={userEmail}/></label></div><button className="btn primary" disabled={saving||fullName.trim().length<2||!/^[a-z0-9][a-z0-9._-]{2,31}$/.test(username)} onClick={()=>void saveProfile()}>Save profile</button></section>}
  {tab==='Notifications'&&<section className="card settings-card"><h2>Notification preferences</h2><p>Choose which operational events should reach you.</p><div className="preference-list">{([['in_app','In-app notifications'],['email_qualified_lead','Qualified leads'],['email_assignment','Lead assignments'],['email_follow_up','Follow-up reminders'],['email_automation_failure','Automation failures'],['email_integration_failure','Integration failures']] as const).map(([key,label])=><label key={key}><span><strong>{label}</strong><small>{key==='in_app'?'Show alerts in Nexara':'Email this event when email delivery is configured'}</small></span><input type="checkbox" checked={preferences[key]} onChange={event=>setPreferences({...preferences,[key]:event.target.checked})}/></label>)}</div><button className="btn primary" disabled={saving} onClick={()=>void savePreferences()}>Save preferences</button></section>}
  {tab==='Security'&&<section className="card settings-card"><h2>Account security</h2><p>Sessions and authentication are protected by Supabase Auth.</p><div className="settings-form"><label>New password<input type="password" minLength={8} value={password} onChange={event=>setPassword(event.target.value)} placeholder="At least 8 characters"/></label></div><button className="btn primary" disabled={password.length<8} onClick={async()=>{const result=await updatePassword(password);notify(result.message??(result.ok?'Password updated':'Unable to update password'));if(result.ok)setPassword('')}}>Update password</button><div className="settings-security"><strong>Tenant protection active</strong><p>Database row-level security limits every query to permitted workspace records.</p></div></section>}
  {tab==='Data & privacy'&&<section className="card settings-card"><h2>Workspace data</h2><p>Download a portable JSON copy of customer and operational records.</p><button className="btn secondary" onClick={()=>void download()}>Download data export</button>{organization.role==='OWNER'&&<div className="danger-zone"><h3>Delete workspace</h3><p>This permanently removes the workspace and its tenant-owned records. Type <strong>{organization.name}</strong> to confirm.</p><input aria-label="Workspace deletion confirmation" value={confirmation} onChange={event=>setConfirmation(event.target.value)}/><button className="btn danger" disabled={confirmation!==organization.name} onClick={async()=>{await deleteWorkspace(organization.id,confirmation);location.reload()}}>Permanently delete workspace</button></div>}</section>}
  </div></div></>
}
