import {useEffect,useState} from 'react'
import {saveOrganizationSettings,type OrganizationSettingsInput,type OrganizationSummary} from '../../services/organizations'

const fromOrganization=(organization:OrganizationSummary):OrganizationSettingsInput=>({name:organization.name,industry:organization.industry??'',website:organization.website??'',phone:organization.phone??'',country:organization.country??'KE',timezone:organization.timezone??'Africa/Nairobi'})

export function SettingsPage({organization,onSaved,notify}:{organization:OrganizationSummary;onSaved:()=>Promise<void>;notify:(message:string)=>void}){
  const [form,setForm]=useState(()=>fromOrganization(organization)),[saving,setSaving]=useState(false),[saved,setSaved]=useState(false)
  const canManage=['OWNER','ADMIN'].includes(organization.role)
  useEffect(()=>setForm(fromOrganization(organization)),[organization])
  const set=<K extends keyof OrganizationSettingsInput>(key:K,value:OrganizationSettingsInput[K])=>{setSaved(false);setForm(current=>({...current,[key]:value}))}
  const save=async()=>{setSaving(true);try{await saveOrganizationSettings(organization.id,form);await onSaved();setSaved(true);notify('Workspace settings saved')}catch(reason){notify(reason instanceof Error?reason.message:'Unable to save settings')}finally{setSaving(false)}}
  return <><div className="page-heading"><div><p className="eyebrow">Workspace administration</p><h1>Settings</h1><p className="subheading">Identity, locale and customer-facing workspace details.</p></div>{canManage&&<button className="btn primary" disabled={saving} onClick={()=>void save()}>{saving?'Saving…':'Save changes'}</button>}</div><div className="settings-layout"><aside className="card settings-nav"><button className="active">Organization</button><button disabled>Profile <small>Account</small></button><button disabled>Security <small>Supabase Auth</small></button><button disabled>Data & privacy <small>Coming next</small></button></aside><div className="settings-content"><section className="card settings-card"><div className="settings-card-head"><div><h2>Organization details</h2><p>Used in assistant context, invitations and customer communication.</p></div>{saved&&<span className="saved-label">✓ Saved</span>}</div><div className="settings-form"><label>Business name<input disabled={!canManage} value={form.name} onChange={event=>set('name',event.target.value)}/></label><label>Industry<input disabled={!canManage} value={form.industry} onChange={event=>set('industry',event.target.value)} placeholder="Real estate"/></label><label>Website<input disabled={!canManage} type="url" value={form.website} onChange={event=>set('website',event.target.value)} placeholder="https://example.com"/></label><label>Phone<input disabled={!canManage} value={form.phone} onChange={event=>set('phone',event.target.value)} placeholder="+254…"/></label><label>Country<select disabled={!canManage} value={form.country} onChange={event=>set('country',event.target.value)}><option value="KE">Kenya</option><option value="UG">Uganda</option><option value="TZ">Tanzania</option><option value="RW">Rwanda</option><option value="OTHER">Other</option></select></label><label>Timezone<select disabled={!canManage} value={form.timezone} onChange={event=>set('timezone',event.target.value)}><option>Africa/Nairobi</option><option>Africa/Kampala</option><option>Africa/Dar_es_Salaam</option><option>Africa/Kigali</option><option>UTC</option></select></label></div></section><section className="card settings-card settings-security"><div><span className="settings-seal">✓</span><h2>Tenant protection active</h2><p>Workspace records are isolated with database row-level security. Provider credentials remain server-side.</p></div><dl><div><dt>Your role</dt><dd>{organization.role}</dd></div><div><dt>Region</dt><dd>{form.timezone}</dd></div><div><dt>Onboarding</dt><dd>{organization.onboarding_completed_at?'Complete':`Step ${organization.onboarding_step}`}</dd></div></dl></section></div></div></>
}
