import {useMemo,useState} from 'react'

type Lead={name:string;interest:string;source:string;stage:string;score:number;value:string;owner:string;createdAt?:string}
const stages=['New','Qualified','Contacted','Meeting','Negotiation','Won','Lost']
const probabilities:Record<string,number>={New:.1,Qualified:.25,Contacted:.4,Meeting:.55,Negotiation:.75,Won:1,Lost:0}
function valueOf(value:string){const clean=value.replaceAll(',',''),numbers=[...clean.matchAll(/[\d.]+/g)].map(match=>Number(match[0])).filter(Number.isFinite);if(!numbers.length)return 0;const average=numbers.reduce((sum,n)=>sum+n,0)/numbers.length;return /m\b/i.test(clean)?average*1_000_000:/k\b/i.test(clean)?average*1_000:average}
const cash=(value:number)=>new Intl.NumberFormat('en-KE',{style:'currency',currency:'KES',notation:value>=1_000_000?'compact':'standard',maximumFractionDigits:1}).format(value)
const percent=(n:number,total:number)=>total?`${(n/total*100).toFixed(1)}%`:'—'

export function Analytics({leads,isDemo=true}:{leads:Lead[];isDemo?:boolean}){
  const [source,setSource]=useState('All'),[owner,setOwner]=useState('All'),[minimum,setMinimum]=useState(0),[group,setGroup]=useState<'source'|'stage'|'owner'>('source'),[selected,setSelected]=useState<string|null>(null),[sort,setSort]=useState('score'),[period,setPeriod]=useState(90),[report,setReport]=useState<'executive'|'acquisition'|'team'>('executive')
  const cutoff=Date.now()-period*86400000
  const periodLeads=leads.filter(lead=>!lead.createdAt||new Date(lead.createdAt).getTime()>=cutoff)
  const filtered=periodLeads.filter(lead=>(source==='All'||lead.source===source)&&(owner==='All'||lead.owner===owner)&&lead.score>=minimum)
  const groups=[...new Set(filtered.map(lead=>lead[group]))].map(name=>({name,count:filtered.filter(lead=>lead[group]===name).length,value:filtered.filter(lead=>lead[group]===name).reduce((sum,lead)=>sum+valueOf(lead.value),0)}))
  const rows=filtered.filter(lead=>selected===null||lead[group]===selected).sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):sort==='value'?valueOf(b.value)-valueOf(a.value):b.score-a.score)
  const won=filtered.filter(lead=>lead.stage==='Won'),pipeline=filtered.filter(lead=>!['Won','Lost'].includes(lead.stage)).reduce((sum,lead)=>sum+valueOf(lead.value),0),forecast=filtered.reduce((sum,lead)=>sum+valueOf(lead.value)*(probabilities[lead.stage]??0),0)
  const sources=useMemo(()=>[...new Set(filtered.map(lead=>lead.source))].map(name=>{const items=filtered.filter(lead=>lead.source===name),wins=items.filter(lead=>lead.stage==='Won');return {name,leads:items.length,qualified:items.filter(lead=>['Qualified','Contacted','Meeting','Negotiation','Won'].includes(lead.stage)).length,wins:wins.length,revenue:wins.reduce((sum,lead)=>sum+valueOf(lead.value),0),average:Math.round(items.reduce((sum,lead)=>sum+lead.score,0)/items.length)}}).sort((a,b)=>b.revenue-a.revenue||b.qualified-a.qualified),[filtered])
  const owners=useMemo(()=>[...new Set(filtered.map(lead=>lead.owner))].map(name=>{const items=filtered.filter(lead=>lead.owner===name);return {name,open:items.filter(lead=>!['Won','Lost'].includes(lead.stage)).length,wins:items.filter(lead=>lead.stage==='Won').length,pipeline:items.reduce((sum,lead)=>sum+valueOf(lead.value),0),average:Math.round(items.reduce((sum,lead)=>sum+lead.score,0)/items.length)}}).sort((a,b)=>b.wins-a.wins||b.pipeline-a.pipeline),[filtered])
  const reset=()=>{setSource('All');setOwner('All');setMinimum(0);setSelected(null);setPeriod(90)}
  const exportCsv=()=>{const quote=(value:string|number)=>`"${String(value).replace(/^[=+@-]/,"'$&").replaceAll('"','""')}"`,data=[['Name','Source','Owner','Stage','Score','Budget (as entered)','Estimated value'],...rows.map(lead=>[lead.name,lead.source,lead.owner,lead.stage,lead.score,lead.value,valueOf(lead.value)])],url=URL.createObjectURL(new Blob(['\uFEFF'+data.map(row=>row.map(quote).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'})),anchor=document.createElement('a');anchor.href=url;anchor.download=isDemo?'leadflow-demo-analytics.csv':'nexara-analytics.csv';anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
  return <div className="analytics-workbench"><div className="page-heading"><div><p className="eyebrow">Revenue intelligence · {isDemo?'Demo workspace':'Live workspace'}</p><h1>Understand your opportunities.</h1><p className="subheading">Use the agency command report to track acquisition quality, team performance and revenue movement.</p></div><button className="btn primary" disabled={!rows.length} onClick={exportCsv}>Export filtered CSV ↓</button></div>
    <div className="report-tabs">{(['executive','acquisition','team'] as const).map(value=><button className={report===value?'active':''} onClick={()=>setReport(value)} key={value}>{value==='executive'?'Executive overview':value==='acquisition'?'Acquisition & funnel':'Team performance'}</button>)}</div>
    <div className="insight-controls card"><label>Period<select aria-label="Analytics date range" value={period} onChange={event=>{setPeriod(Number(event.target.value));setSelected(null)}}><option value={7}>Last 7 days</option><option value={30}>Last 30 days</option><option value={90}>Last 90 days</option><option value={3650}>All time</option></select></label><label>Source<select value={source} onChange={event=>{setSource(event.target.value);setSelected(null)}}>{['All',...new Set(leads.map(lead=>lead.source))].map(value=><option key={value}>{value}</option>)}</select></label><label>Owner<select value={owner} onChange={event=>{setOwner(event.target.value);setSelected(null)}}>{['All',...new Set(leads.map(lead=>lead.owner))].map(value=><option key={value}>{value}</option>)}</select></label><label>Minimum score: {minimum}<input aria-label="Minimum score" type="range" min="0" max="100" value={minimum} onChange={event=>{setMinimum(Number(event.target.value));setSelected(null)}}/></label><button className="btn secondary" onClick={reset}>Reset filters</button></div>
    <div className="metric-grid analytics-metrics">{[['Open pipeline',cash(pipeline)],['Weighted forecast',cash(forecast)],['Won revenue',cash(won.reduce((sum,lead)=>sum+valueOf(lead.value),0))],['Lead-to-win',percent(won.length,filtered.length)],['Average score',filtered.length?Math.round(filtered.reduce((sum,lead)=>sum+lead.score,0)/filtered.length):'—']].map(([label,value])=><div className="card metric" key={label}><div className="metric-top">{label}</div><strong>{value}</strong></div>)}</div>
    {report==='executive'&&<><div className="insights-layout"><section className="card insight-panel"><div className="card-head"><div><h2>Pipeline composition</h2><p>Volume and potential value by {group}.</p></div><select aria-label="Group leads by" value={group} onChange={event=>{setGroup(event.target.value as typeof group);setSelected(null)}}><option value="source">source</option><option value="stage">stage</option><option value="owner">owner</option></select></div><div className="breakdown">{groups.map(item=><button key={item.name} aria-pressed={selected===item.name} onClick={()=>setSelected(selected===item.name?null:item.name)}><span>{item.name}<small>{cash(item.value)}</small></span><strong>{item.count} · {percent(item.count,filtered.length)}</strong><i style={{width:percent(item.count,filtered.length)}}/></button>)}</div></section><section className="card insight-panel"><div className="card-head"><div><h2>Forecast confidence</h2><p>Stage-weighted, not an accounting projection.</p></div></div><div className="health-summary"><strong>{cash(forecast)}</strong><span>weighted pipeline</span><p>{filtered.filter(lead=>lead.owner==='Unassigned').length} unassigned opportunities.</p><p>{filtered.filter(lead=>!valueOf(lead.value)).length} records without a usable deal value.</p><p>{filtered.filter(lead=>lead.stage==='New').length} leads awaiting qualification.</p></div></section></div><StageFunnel leads={filtered}/></>}
    {report==='acquisition'&&<section className="card insight-panel scorecard"><div className="card-head"><div><h2>Source quality scorecard</h2><p>Compare volume, qualification and attributable wins.</p></div></div><div className="table-wrap"><table className="report-table"><thead><tr><th>Source</th><th>Leads</th><th>Qualified</th><th>Qualification rate</th><th>Wins</th><th>Won revenue</th><th>Avg. score</th></tr></thead><tbody>{sources.map(item=><tr key={item.name}><td><strong>{item.name}</strong></td><td>{item.leads}</td><td>{item.qualified}</td><td>{percent(item.qualified,item.leads)}</td><td>{item.wins}</td><td>{cash(item.revenue)}</td><td>{item.average}</td></tr>)}</tbody></table></div></section>}
    {report==='team'&&<section className="owner-scorecards">{owners.map((item,index)=><article className="card" key={item.name}><span className="owner-rank">#{index+1}</span><h2>{item.name}</h2><strong>{item.wins} won</strong><div><span>{item.open} open opportunities</span><span>{cash(item.pipeline)} portfolio</span><span>{item.average} average score</span></div></article>)}</section>}
    <section className="card insight-panel"><div className="card-head"><div><h2>Opportunity details {selected&&`· ${selected}`}</h2><p>{rows.length} matching records · values inferred from entered budgets</p></div><label>Sort <select value={sort} onChange={event=>setSort(event.target.value)}><option value="score">Highest score</option><option value="value">Highest value</option><option value="name">Name A–Z</option></select></label></div><div className="table-wrap"><table className="report-table"><thead><tr>{['Lead','Source','Owner','Stage','Score','Budget','Weighted value'].map(header=><th key={header}>{header}</th>)}</tr></thead><tbody>{rows.map((lead,index)=><tr key={lead.name+index}><td>{lead.name}</td><td>{lead.source}</td><td>{lead.owner}</td><td>{lead.stage}</td><td>{lead.score}</td><td>{lead.value}</td><td>{cash(valueOf(lead.value)*(probabilities[lead.stage]??0))}</td></tr>)}</tbody></table>{!rows.length&&<p className="table-empty">No matching leads.</p>}</div></section><p className="report-footnote">Forecasts use visible deal values and standard stage probabilities. They are directional management tools, not booked revenue. {isDemo?'This report contains fictional demo data.':'This report uses your live workspace records.'}</p></div>
}
function StageFunnel({leads}:{leads:Lead[]}){const counts=stages.map(stage=>({stage,count:leads.filter(lead=>lead.stage===stage).length,value:leads.filter(lead=>lead.stage===stage).reduce((sum,lead)=>sum+valueOf(lead.value),0)}));return <section className="card stage-funnel"><div className="card-head"><div><h2>Funnel leakage</h2><p>See where current opportunities are concentrated.</p></div></div><div>{counts.map(item=><div key={item.stage}><span>{item.stage}</span><i><b style={{width:percent(item.count,Math.max(...counts.map(value=>value.count),1))}}/></i><strong>{item.count}</strong><small>{cash(item.value)}</small></div>)}</div></section>}
