import {useCallback,useEffect,useState} from 'react'
import {createLeadSource,deleteLeadSource,listLeadSources,rotateLeadSourceKey,setLeadSourceStatus} from '../../services/leadSources'
import type {LeadSourceRow} from '../../types/database'
import {supabase} from '../../lib/supabase'
import './source-connectors.css'

const platforms=['Instagram','Facebook Lead Ads','Messenger','LinkedIn','TikTok Lead Ads','X / Twitter','Google Ads','Google Business Profile','YouTube','Shopify','WooCommerce','Calendly','Typeform','Jotform','Marketplace / directory','Zapier','Make','n8n','Custom API']
const endpoint=`${import.meta.env.VITE_SUPABASE_URL??'https://YOUR_PROJECT.supabase.co'}/functions/v1/source-ingest`
const sample=(sourceId:string)=>JSON.stringify({sourceId,name:'Jane Customer',email:'jane@company.com',phone:'+254700000000',company:'Example Company',interest:'Tell us what the customer needs',estimatedValue:150000,externalId:'platform-record-id',metadata:{campaign:'Q4 growth'}},null,2)

export function SourceConnectors({organizationId,canManage,notify}:{organizationId:string;canManage:boolean;notify:(message:string)=>void}){
  const [items,setItems]=useState<LeadSourceRow[]>([]),[creating,setCreating]=useState(false),[name,setName]=useState(''),[platform,setPlatform]=useState(platforms[0]),[credential,setCredential]=useState<{source:LeadSourceRow;token:string}|null>(null),[busy,setBusy]=useState(false)
  const refresh=useCallback(()=>listLeadSources(organizationId).then(setItems).catch(reason=>notify(reason instanceof Error?reason.message:'Unable to load inbound sources')),[organizationId,notify])
  useEffect(()=>{void refresh()},[refresh])
  useEffect(()=>{if(!supabase)return;const client=supabase,channel=client.channel(`lead-sources:${organizationId}`).on('postgres_changes',{event:'*',schema:'public',table:'lead_sources',filter:`organization_id=eq.${organizationId}`},()=>void refresh()).subscribe();return()=>{void client.removeChannel(channel)}},[organizationId,refresh])
  const create=async()=>{setBusy(true);try{const result=await createLeadSource(organizationId,name,platform);setCredential(result);setCreating(false);setName('');await refresh();notify(`${platform} source created`)}catch(reason){notify(reason instanceof Error?reason.message:'Unable to create source')}finally{setBusy(false)}}
  const copy=async(value:string,label:string)=>{await navigator.clipboard.writeText(value);notify(`${label} copied`)}
  return <section className="card source-connectors"><div className="card-head"><div><p className="eyebrow">Universal inbound compatibility</p><h2>Customer source connectors</h2><p>Connect any platform that can send a webhook—or route it through Zapier, Make or n8n.</p></div><button className="btn primary" disabled={!canManage} onClick={()=>setCreating(true)}>＋ Add source</button></div><div className="connector-platforms">{platforms.map(value=><span key={value}>{value}</span>)}</div><div className="source-list">{items.map(item=><article key={item.id}><span className="source-platform-icon">↗</span><div><strong>{item.name}</strong><small>{item.platform} · {item.last_received_at?`last lead ${new Date(item.last_received_at).toLocaleString()}`:'waiting for first lead'}</small></div><span className={`source-state ${item.status.toLowerCase()}`}>{item.status}</span>{canManage&&<><button className="btn secondary" onClick={async()=>{const token=await rotateLeadSourceKey(organizationId,item.id);setCredential({source:item,token});notify('Source key rotated; the previous key no longer works')}}>Rotate key</button><button className="text-btn" onClick={async()=>{await setLeadSourceStatus(organizationId,item.id,item.status==='ACTIVE'?'PAUSED':'ACTIVE');await refresh()}}>{item.status==='ACTIVE'?'Pause':'Activate'}</button><button className="text-btn danger-text" onClick={async()=>{if(!confirm(`Delete ${item.name}? Its current endpoint key will stop working.`))return;await deleteLeadSource(organizationId,item.id);await refresh();notify('Source deleted')}}>Delete</button></>}</article>)}{!items.length&&<div className="source-empty"><strong>Bring leads in from anywhere</strong><p>Create a source, copy its endpoint credentials, then map the platform’s customer fields to the sample payload.</p></div>}</div><div className="connector-boundary"><strong>How compatibility works</strong><span><b>Native</b> Website and WhatsApp use dedicated product connectors.</span><span><b>Universal</b> Every other platform uses this authenticated inbound endpoint directly or through a no-code bridge.</span><span><b>Attribution</b> The source name and platform stay attached to every created lead.</span></div>
    {creating&&<div className="modal-backdrop" onMouseDown={()=>setCreating(false)}><form className="modal source-dialog" onMouseDown={event=>event.stopPropagation()} onSubmit={event=>{event.preventDefault();void create()}}><div className="modal-head"><div><p className="eyebrow">New inbound source</p><h2>Connect a customer platform</h2></div><button type="button" className="close" onClick={()=>setCreating(false)}>×</button></div><div className="source-form"><label>Platform<select value={platform} onChange={event=>setPlatform(event.target.value)}>{platforms.map(value=><option key={value}>{value}</option>)}</select></label><label>Source name<input autoFocus required minLength={2} maxLength={80} value={name} onChange={event=>setName(event.target.value)} placeholder="e.g. LinkedIn enterprise campaign"/></label><p>This name appears in CRM source filters and attribution reports.</p></div><div className="modal-actions"><button type="button" className="btn secondary" onClick={()=>setCreating(false)}>Cancel</button><button className="btn primary" disabled={busy||name.trim().length<2}>{busy?'Creating…':'Create secure source'}</button></div></form></div>}
    {credential&&<div className="modal-backdrop"><section className="modal credential-dialog" role="dialog" aria-modal="true" aria-labelledby="credential-title"><div className="modal-head"><div><p className="eyebrow">Shown once</p><h2 id="credential-title">Connect {credential.source.name}</h2></div><button className="close" onClick={()=>setCredential(null)}>×</button></div><div className="credential-warning">Copy this key now. Nexara stores only its secure hash and cannot show it again.</div><label>Endpoint<div><input readOnly value={endpoint}/><button className="btn secondary" onClick={()=>void copy(endpoint,'Endpoint')}>Copy</button></div></label><label>Header: x-nexara-source-key<div><input readOnly value={credential.token}/><button className="btn secondary" onClick={()=>void copy(credential.token,'Source key')}>Copy</button></div></label><label>JSON body<textarea readOnly value={sample(credential.source.id)}/><button className="btn secondary" onClick={()=>void copy(sample(credential.source.id),'Sample payload')}>Copy payload</button></label><div className="modal-actions"><button className="btn primary" onClick={()=>setCredential(null)}>I saved the key</button></div></section></div>}
  </section>
}
