import {useEffect,useState} from 'react'
import type {CSSProperties} from 'react'
import {getWidgetConfig,saveWidgetConfig} from '../../services/workspaceAdmin'
import type {WidgetConfigRow} from '../../types/database'

const demoKey='nexara-demo-widget'
const defaults=(organizationId:string):WidgetConfigRow=>({organization_id:organizationId,public_key:crypto.randomUUID(),enabled:false,brand_name:'Nexara Assistant',welcome_message:'Hi! What are you looking for today?',primary_color:'#6d5dfc',allowed_origins:[],updated_at:new Date().toISOString()})
export function WidgetBuilder({organizationId,notify}:{organizationId?:string;notify:(message:string)=>void}){
  const [config,setConfig]=useState<WidgetConfigRow>(()=>{try{return JSON.parse(localStorage.getItem(demoKey)??'null')??defaults('demo')}catch{return defaults('demo')}}),[origin,setOrigin]=useState(''),[saving,setSaving]=useState(false),[copied,setCopied]=useState(false)
  useEffect(()=>{if(organizationId)void getWidgetConfig(organizationId).then(value=>setConfig(value??defaults(organizationId)))},[organizationId])
  const save=async()=>{setSaving(true);try{const next={...config,organization_id:organizationId??'demo',allowed_origins:[...new Set(config.allowed_origins.map(value=>value.trim()).filter(Boolean))],updated_at:new Date().toISOString()};if(organizationId)setConfig(await saveWidgetConfig(next));else{localStorage.setItem(demoKey,JSON.stringify(next));setConfig(next)}notify('Website widget configuration saved')}catch(reason){notify(reason instanceof Error?reason.message:'Unable to save widget')}finally{setSaving(false)}}
  const endpoint=`${import.meta.env.VITE_SUPABASE_URL??'https://YOUR_PROJECT.supabase.co'}/functions/v1/widget-inquiry`,snippet=`<script src="${location.origin}/nexara-widget.js" data-widget-key="${config.public_key}" data-endpoint="${endpoint}" async></script>`
  return <section className="card widget-builder"><div className="card-head"><div><p className="eyebrow">Embeddable lead capture</p><h2>Website chat widget</h2><p>Brand the launcher, restrict allowed websites and copy the installation snippet.</p></div><button className={config.enabled?'status-toggle on':'status-toggle'} onClick={()=>setConfig({...config,enabled:!config.enabled})}><i/>{config.enabled?'Active':'Paused'}</button></div><div className="widget-layout"><div className="widget-form"><label>Assistant name<input value={config.brand_name} onChange={event=>setConfig({...config,brand_name:event.target.value})}/></label><label>Welcome message<textarea value={config.welcome_message} onChange={event=>setConfig({...config,welcome_message:event.target.value})}/></label><label>Brand colour<input type="color" value={config.primary_color} onChange={event=>setConfig({...config,primary_color:event.target.value})}/></label><label>Allowed website origin<div className="inline-control"><input value={origin} onChange={event=>setOrigin(event.target.value)} placeholder="https://yourbusiness.com"/><button className="btn secondary" disabled={!origin.startsWith('https://')} onClick={()=>{setConfig({...config,allowed_origins:[...config.allowed_origins,origin]});setOrigin('')}}>Add</button></div></label><div className="origin-chips">{config.allowed_origins.map(value=><button key={value} onClick={()=>setConfig({...config,allowed_origins:config.allowed_origins.filter(item=>item!==value)})}>{value} ×</button>)}</div><button className="btn primary" disabled={saving||config.brand_name.trim().length<2||config.enabled&&!config.allowed_origins.length} onClick={()=>void save()}>{saving?'Saving…':'Save widget'}</button></div><div className="widget-preview" style={{'--widget-color':config.primary_color} as CSSProperties}><div className="widget-chat"><strong>{config.brand_name}</strong><p>{config.welcome_message}</p><input disabled placeholder="Type your message…"/></div><button aria-label="Widget launcher">✦</button></div></div><label className="embed-code">Install snippet<textarea readOnly value={snippet}/><button className="btn secondary" onClick={async()=>{await navigator.clipboard.writeText(snippet);setCopied(true)}}>{copied?'Copied ✓':'Copy snippet'}</button></label><p className="data-note">Only configured HTTPS origins should embed this key. Submissions enter the secure public-inquiry service and create a lead.</p></section>
}
